# generate-api-client.ps1
# Downloads the OpenAPI schema from the dev backend and regenerates the Rust client crate.
#
# Usage:
#   .\generate-api-client.ps1                    # default: downloads from localhost:8000
#   .\generate-api-client.ps1 -SchemaUrl "http://other-host:8000/schema/"
#   .\generate-api-client.ps1 -SkipDownload      # regenerate from existing schema file

param(
    [string]$SchemaUrl = "http://localhost:8000/schema/?format=yaml",
    [switch]$SkipDownload
)

$ErrorActionPreference = "Stop"

$projectRoot = $PSScriptRoot
$schemaFile  = Join-Path $projectRoot "reckon-schema.yaml"
$outputDir   = Join-Path $projectRoot "reckon-api"

# ── 1. Download the schema ──────────────────────────────────────────────────
if (-not $SkipDownload) {
    Write-Host "Downloading OpenAPI schema from $SchemaUrl ..." -ForegroundColor Cyan
    try {
        Invoke-RestMethod -Uri $SchemaUrl -OutFile $schemaFile -TimeoutSec 30
        Write-Host "Schema saved to $schemaFile" -ForegroundColor Green
    }
    catch {
        Write-Error "Failed to download schema: $_"
        exit 1
    }
}
else {
    if (-not (Test-Path $schemaFile)) {
        Write-Error "Schema file not found at $schemaFile. Run without -SkipDownload first."
        exit 1
    }
    Write-Host "Skipping download, using existing $schemaFile" -ForegroundColor Yellow
}

# ── 2. Clean previous generation (keep Cargo.toml tweaks if any) ────────────
if (Test-Path $outputDir) {
    Write-Host "Removing previous generated client..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force $outputDir
}

# ── 3. Run openapi-generator ────────────────────────────────────────────────
Write-Host "Generating Rust client in $outputDir ..." -ForegroundColor Cyan

try {
    $configFile_gen = Join-Path $projectRoot "openapi-generator-config.yaml"
    & openapi-generator-cli generate `
        -i $schemaFile `
        -g rust `
        -c $configFile_gen `
        -o $outputDir `
        --skip-validate-spec
    if ($LASTEXITCODE -ne 0) {
        Write-Error "openapi-generator exited with code $LASTEXITCODE"
        exit 1
    }
}
catch {
    Write-Error "Failed to run openapi-generator-cli. Make sure it is installed: npm install -g @openapitools/openapi-generator-cli`n$_"
    exit 1
}

# ── 4. Post-generation fixes ─────────────────────────────────────────────────
# Fix known openapi-generator bug: `models::serde_json::Value` → `serde_json::Value`
Write-Host "Applying post-generation fixes..." -ForegroundColor Cyan
$apiDir = Join-Path (Join-Path $outputDir "src") "apis"
Get-ChildItem -Path $apiDir -Filter "*.rs" | ForEach-Object {
    $content = Get-Content $_.FullName -Raw
    if ($content -match 'models::serde_json::Value') {
        $content = $content -replace 'models::serde_json::Value', 'serde_json::Value'
        Set-Content -Path $_.FullName -Value $content -NoNewline
        Write-Host "  Fixed $($_.Name)" -ForegroundColor Gray
    }
}

# ── 5. Patch Configuration to support dev/prod base URLs ─────────────────────
$configFile = Join-Path (Join-Path (Join-Path $outputDir "src") "apis") "configuration.rs"
Write-Host "Patching Configuration with dev/prod base URLs..." -ForegroundColor Cyan

$configContent = @'
/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */


/// Base URL for the development backend (localhost).
pub const BASE_URL_DEV: &str = "http://localhost:8000";

/// Base URL for the production backend.
pub const BASE_URL_PROD: &str = "https://api.reckon-bolt.com";

#[derive(Debug, Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub bearer_access_token: Option<String>,
    pub api_key: Option<ApiKey>,
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }

    /// Create a configuration pointing at the **development** backend.
    pub fn dev() -> Configuration {
        Configuration {
            base_path: BASE_URL_DEV.to_owned(),
            ..Default::default()
        }
    }

    /// Create a configuration pointing at the **production** backend.
    pub fn prod() -> Configuration {
        Configuration {
            base_path: BASE_URL_PROD.to_owned(),
            ..Default::default()
        }
    }

    /// Create a configuration with a custom base URL.
    pub fn with_base_url(base_url: &str) -> Configuration {
        Configuration {
            base_path: base_url.to_owned(),
            ..Default::default()
        }
    }

    /// Set the API token for authentication (token auth).
    pub fn with_token(mut self, token: &str) -> Configuration {
        self.api_key = Some(ApiKey {
            prefix: Some("Token".to_owned()),
            key: token.to_owned(),
        });
        self
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: BASE_URL_DEV.to_owned(),
            user_agent: Some("ReckonBoltApp/1.0.0".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: None,
            api_key: None,
        }
    }
}
'@
Set-Content -Path $configFile -Value $configContent -NoNewline

Write-Host "`nRust client generated successfully in $outputDir" -ForegroundColor Green
Write-Host "Don't forget to run 'cargo check' in src-tauri/ to verify compilation." -ForegroundColor Cyan
