/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddAccount {
    /// Account puuid
    #[serde(rename = "puuid")]
    pub puuid: String,
    /// Account name, in the form of riotId#riotTagline
    #[serde(rename = "account_name", skip_serializing_if = "Option::is_none")]
    pub account_name: Option<String>,
}

impl AddAccount {
    pub fn new(puuid: String) -> AddAccount {
        AddAccount {
            puuid,
            account_name: None,
        }
    }
}

