/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddAccount {
    /// Account name in {riot_id}-{tagline} form
    #[serde(rename = "account_name")]
    pub account_name: String,
    /// Server of the account
    #[serde(rename = "server")]
    pub server: String,
    /// Source of the information
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl AddAccount {
    pub fn new(account_name: String, server: String) -> AddAccount {
        AddAccount {
            account_name,
            server,
            source: None,
        }
    }
}

