/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientOrganizationVariableDistribution200ResponseInner : Successful response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientOrganizationVariableDistribution200ResponseInner {
    #[serde(rename = "bucket", skip_serializing_if = "Option::is_none")]
    pub bucket: Option<i32>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "proportion", skip_serializing_if = "Option::is_none")]
    pub proportion: Option<f64>,
}

impl ClientOrganizationVariableDistribution200ResponseInner {
    /// Successful response
    pub fn new() -> ClientOrganizationVariableDistribution200ResponseInner {
        ClientOrganizationVariableDistribution200ResponseInner {
            bucket: None,
            count: None,
            proportion: None,
        }
    }
}

