/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientOrganization {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "teams")]
    pub teams: String,
    #[serde(rename = "grid_api_key")]
    pub grid_api_key: String,
    #[serde(rename = "plan")]
    pub plan: String,
    #[serde(rename = "subscription_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subscription_date: Option<Option<String>>,
    #[serde(rename = "subscription_ends", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subscription_ends: Option<Option<String>>,
}

impl ClientOrganization {
    pub fn new(id: String, teams: String, grid_api_key: String, plan: String) -> ClientOrganization {
        ClientOrganization {
            id,
            teams,
            grid_api_key,
            plan,
            subscription_date: None,
            subscription_ends: None,
        }
    }
}

