/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesOtherAbilitiesInner {
    #[serde(rename = "cast_position")]
    pub cast_position: Box<models::CompetitiveRoundSummariesSmokeAbilitiesInnerCastPosition>,
    #[serde(rename = "slot")]
    pub slot: String,
}

impl CompetitiveRoundSummariesOtherAbilitiesInner {
    pub fn new(cast_position: models::CompetitiveRoundSummariesSmokeAbilitiesInnerCastPosition, slot: String) -> CompetitiveRoundSummariesOtherAbilitiesInner {
        CompetitiveRoundSummariesOtherAbilitiesInner {
            cast_position: Box::new(cast_position),
            slot,
        }
    }
}

