/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItemAmmunition {
    #[serde(rename = "in_magazine", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_magazine: Option<Option<i32>>,
    #[serde(rename = "in_reserve", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_reserve: Option<Option<i32>>,
}

impl CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItemAmmunition {
    pub fn new() -> CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItemAmmunition {
        CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItemAmmunition {
            in_magazine: None,
            in_reserve: None,
        }
    }
}

