/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesSmokeAbilitiesInner {
    #[serde(rename = "cast_position")]
    pub cast_position: Box<models::CompetitiveRoundSummariesSmokeAbilitiesInnerCastPosition>,
    #[serde(rename = "duration")]
    pub duration: f64,
    #[serde(rename = "landing_point")]
    pub landing_point: Box<models::CompetitiveRoundSummariesSmokeAbilitiesInnerLandingPoint>,
    #[serde(rename = "is_inferred")]
    pub is_inferred: bool,
    #[serde(rename = "slot")]
    pub slot: String,
}

impl CompetitiveRoundSummariesSmokeAbilitiesInner {
    pub fn new(cast_position: models::CompetitiveRoundSummariesSmokeAbilitiesInnerCastPosition, duration: f64, landing_point: models::CompetitiveRoundSummariesSmokeAbilitiesInnerLandingPoint, is_inferred: bool, slot: String) -> CompetitiveRoundSummariesSmokeAbilitiesInner {
        CompetitiveRoundSummariesSmokeAbilitiesInner {
            cast_position: Box::new(cast_position),
            duration,
            landing_point: Box::new(landing_point),
            is_inferred,
            slot,
        }
    }
}

