/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesDeathEventAgnosticInner {
    #[serde(rename = "killer_location")]
    pub killer_location: Box<models::CompetitiveRoundSummariesDeathEventAgnosticInnerKillerLocation>,
    #[serde(rename = "killer_weapon", deserialize_with = "Option::deserialize")]
    pub killer_weapon: Option<String>,
    #[serde(rename = "killer_ability", deserialize_with = "Option::deserialize")]
    pub killer_ability: Option<String>,
    #[serde(rename = "was_traded")]
    pub was_traded: bool,
    #[serde(rename = "is_first_blood")]
    pub is_first_blood: bool,
    #[serde(rename = "is_first_true_blood")]
    pub is_first_true_blood: bool,
    #[serde(rename = "victim_agent")]
    pub victim_agent: String,
    #[serde(rename = "victim_weapon")]
    pub victim_weapon: String,
    #[serde(rename = "victim_location")]
    pub victim_location: Box<models::CompetitiveRoundSummariesDeathEventAgnosticInnerVictimLocation>,
    #[serde(rename = "time_in_round")]
    pub time_in_round: f64,
    #[serde(rename = "situation_before_kill")]
    pub situation_before_kill: String,
    #[serde(rename = "situation_after_kill")]
    pub situation_after_kill: String,
}

impl CompetitiveRoundSummariesDeathEventAgnosticInner {
    pub fn new(killer_location: models::CompetitiveRoundSummariesDeathEventAgnosticInnerKillerLocation, killer_weapon: Option<String>, killer_ability: Option<String>, was_traded: bool, is_first_blood: bool, is_first_true_blood: bool, victim_agent: String, victim_weapon: String, victim_location: models::CompetitiveRoundSummariesDeathEventAgnosticInnerVictimLocation, time_in_round: f64, situation_before_kill: String, situation_after_kill: String) -> CompetitiveRoundSummariesDeathEventAgnosticInner {
        CompetitiveRoundSummariesDeathEventAgnosticInner {
            killer_location: Box::new(killer_location),
            killer_weapon,
            killer_ability,
            was_traded,
            is_first_blood,
            is_first_true_blood,
            victim_agent,
            victim_weapon,
            victim_location: Box::new(victim_location),
            time_in_round,
            situation_before_kill,
            situation_after_kill,
        }
    }
}

