/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveTiersAggregate {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tier")]
    pub tier: i32,
    #[serde(rename = "division", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub division: Option<Option<String>>,
    #[serde(rename = "color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color: Option<Option<String>>,
    #[serde(rename = "background_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub background_color: Option<Option<String>>,
    #[serde(rename = "small_icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub small_icon: Option<Option<String>>,
    #[serde(rename = "large_icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub large_icon: Option<Option<String>>,
}

impl CompetitiveTiersAggregate {
    pub fn new(id: String, tier: i32) -> CompetitiveTiersAggregate {
        CompetitiveTiersAggregate {
            id,
            tier,
            division: None,
            color: None,
            background_color: None,
            small_icon: None,
            large_icon: None,
        }
    }
}

