/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesDeathEventAgnosticInnerKillerLocationPosition {
    #[serde(rename = "x", deserialize_with = "Option::deserialize")]
    pub x: Option<f64>,
    #[serde(rename = "y", deserialize_with = "Option::deserialize")]
    pub y: Option<f64>,
}

impl CompetitiveRoundSummariesDeathEventAgnosticInnerKillerLocationPosition {
    pub fn new(x: Option<f64>, y: Option<f64>) -> CompetitiveRoundSummariesDeathEventAgnosticInnerKillerLocationPosition {
        CompetitiveRoundSummariesDeathEventAgnosticInnerKillerLocationPosition {
            x,
            y,
        }
    }
}

