/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesPlayerSnapshotsInner {
    #[serde(rename = "alive_state")]
    pub alive_state: Box<models::CompetitiveRoundSummariesPlayerSnapshotsInnerAliveState>,
    #[serde(rename = "abilities")]
    pub abilities: std::collections::HashMap<String, models::CompetitiveRoundSummariesPlayerSnapshotsInnerAbilitiesValue>,
    #[serde(rename = "kills")]
    pub kills: i32,
    #[serde(rename = "deaths")]
    pub deaths: i32,
    #[serde(rename = "assists")]
    pub assists: i32,
    #[serde(rename = "money")]
    pub money: i32,
    #[serde(rename = "loadout_value")]
    pub loadout_value: i32,
    #[serde(rename = "inventory")]
    pub inventory: std::collections::HashMap<String, models::CompetitiveRoundSummariesPlayerSnapshotsInnerInventoryValue>,
    #[serde(rename = "scores")]
    pub scores: Box<models::CompetitiveRoundSummariesPlayerSnapshotsInnerScores>,
}

impl CompetitiveRoundSummariesPlayerSnapshotsInner {
    pub fn new(alive_state: models::CompetitiveRoundSummariesPlayerSnapshotsInnerAliveState, abilities: std::collections::HashMap<String, models::CompetitiveRoundSummariesPlayerSnapshotsInnerAbilitiesValue>, kills: i32, deaths: i32, assists: i32, money: i32, loadout_value: i32, inventory: std::collections::HashMap<String, models::CompetitiveRoundSummariesPlayerSnapshotsInnerInventoryValue>, scores: models::CompetitiveRoundSummariesPlayerSnapshotsInnerScores) -> CompetitiveRoundSummariesPlayerSnapshotsInner {
        CompetitiveRoundSummariesPlayerSnapshotsInner {
            alive_state: Box::new(alive_state),
            abilities,
            kills,
            deaths,
            assists,
            money,
            loadout_value,
            inventory,
            scores: Box::new(scores),
        }
    }
}

