/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesDeathEventInnerKillerLocation {
    #[serde(rename = "position")]
    pub position: Box<models::CompetitiveRoundSummariesDeathEventInnerKillerLocationPosition>,
    #[serde(rename = "viewVector")]
    pub view_vector: Box<models::CompetitiveRoundSummariesDeathEventInnerKillerLocationPosition>,
    #[serde(rename = "velocity")]
    pub velocity: Box<models::CompetitiveRoundSummariesDeathEventInnerKillerLocationPosition>,
    #[serde(rename = "timestamp", deserialize_with = "Option::deserialize")]
    pub timestamp: Option<f64>,
    #[serde(rename = "time_in_round", deserialize_with = "Option::deserialize")]
    pub time_in_round: Option<f64>,
}

impl CompetitiveRoundSummariesDeathEventInnerKillerLocation {
    pub fn new(position: models::CompetitiveRoundSummariesDeathEventInnerKillerLocationPosition, view_vector: models::CompetitiveRoundSummariesDeathEventInnerKillerLocationPosition, velocity: models::CompetitiveRoundSummariesDeathEventInnerKillerLocationPosition, timestamp: Option<f64>, time_in_round: Option<f64>) -> CompetitiveRoundSummariesDeathEventInnerKillerLocation {
        CompetitiveRoundSummariesDeathEventInnerKillerLocation {
            position: Box::new(position),
            view_vector: Box::new(view_vector),
            velocity: Box::new(velocity),
            timestamp,
            time_in_round,
        }
    }
}

