/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesDeathEventAgnosticInnerVictimLocation {
    #[serde(rename = "x")]
    pub x: f64,
    #[serde(rename = "y")]
    pub y: f64,
}

impl CompetitiveRoundSummariesDeathEventAgnosticInnerVictimLocation {
    pub fn new(x: f64, y: f64) -> CompetitiveRoundSummariesDeathEventAgnosticInnerVictimLocation {
        CompetitiveRoundSummariesDeathEventAgnosticInnerVictimLocation {
            x,
            y,
        }
    }
}

