/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveGames {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "game_id")]
    pub game_id: String,
    #[serde(rename = "agnostic_match_history", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub agnostic_match_history: Option<Option<String>>,
    #[serde(rename = "livestats_data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub livestats_data: Option<Option<String>>,
    #[serde(rename = "grid_endgame", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub grid_endgame: Option<Option<String>>,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "score_team1")]
    pub score_team1: i32,
    #[serde(rename = "score_team2")]
    pub score_team2: i32,
    #[serde(rename = "split")]
    pub split: String,
    #[serde(rename = "phase")]
    pub phase: String,
    #[serde(rename = "game_n")]
    pub game_n: i32,
    #[serde(rename = "series_id")]
    pub series_id: i64,
    #[serde(rename = "team1_agents")]
    pub team1_agents: String,
    #[serde(rename = "team2_agents")]
    pub team2_agents: String,
    #[serde(rename = "vod_yt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vod_yt: Option<Option<String>>,
    #[serde(rename = "vod_file", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vod_file: Option<Option<String>>,
    #[serde(rename = "smokes_yolonet_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub smokes_yolonet_version: Option<Option<String>>,
    #[serde(rename = "utils_yolonet_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub utils_yolonet_version: Option<Option<String>>,
    #[serde(rename = "jett_parser_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub jett_parser_version: Option<Option<i32>>,
    #[serde(rename = "team1")]
    pub team1: String,
    #[serde(rename = "team2")]
    pub team2: String,
    #[serde(rename = "map_selection", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub map_selection: Option<Option<String>>,
    #[serde(rename = "winner")]
    pub winner: String,
    #[serde(rename = "league")]
    pub league: String,
    #[serde(rename = "map")]
    pub map: String,
}

impl CompetitiveGames {
    pub fn new(id: String, game_id: String, date: String, score_team1: i32, score_team2: i32, split: String, phase: String, game_n: i32, series_id: i64, team1_agents: String, team2_agents: String, team1: String, team2: String, winner: String, league: String, map: String) -> CompetitiveGames {
        CompetitiveGames {
            id,
            game_id,
            agnostic_match_history: None,
            livestats_data: None,
            grid_endgame: None,
            date,
            score_team1,
            score_team2,
            split,
            phase,
            game_n,
            series_id,
            team1_agents,
            team2_agents,
            vod_yt: None,
            vod_file: None,
            smokes_yolonet_version: None,
            utils_yolonet_version: None,
            jett_parser_version: None,
            team1,
            team2,
            map_selection: None,
            winner,
            league,
            map,
        }
    }
}

