/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveDraftSlots {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "split")]
    pub split: String,
    #[serde(rename = "phase")]
    pub phase: String,
    #[serde(rename = "series")]
    pub series: i32,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "draft_action_id")]
    pub draft_action_id: String,
    #[serde(rename = "teams", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Option<String>>,
    #[serde(rename = "league")]
    pub league: String,
    #[serde(rename = "team1")]
    pub team1: String,
    #[serde(rename = "team2")]
    pub team2: String,
    #[serde(rename = "map")]
    pub map: String,
}

impl CompetitiveDraftSlots {
    pub fn new(id: i32, date: String, split: String, phase: String, series: i32, r#type: String, draft_action_id: String, league: String, team1: String, team2: String, map: String) -> CompetitiveDraftSlots {
        CompetitiveDraftSlots {
            id,
            date,
            split,
            phase,
            series,
            r#type,
            draft_action_id,
            teams: None,
            league,
            team1,
            team2,
            map,
        }
    }
}

