/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesPlayerSnapshotsInnerInventoryValue {
    #[serde(rename = "ammunition")]
    pub ammunition: Box<models::CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItemAmmunition>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slot")]
    pub slot: String,
}

impl CompetitiveRoundSummariesPlayerSnapshotsInnerInventoryValue {
    pub fn new(ammunition: models::CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItemAmmunition, id: String, name: String, slot: String) -> CompetitiveRoundSummariesPlayerSnapshotsInnerInventoryValue {
        CompetitiveRoundSummariesPlayerSnapshotsInnerInventoryValue {
            ammunition: Box::new(ammunition),
            id,
            name,
            slot,
        }
    }
}

