/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesUtilityAbilitiesInner {
    #[serde(rename = "cast_position")]
    pub cast_position: Box<models::CompetitiveRoundSummariesSmokeAbilitiesInnerCastPosition>,
    #[serde(rename = "landing_point")]
    pub landing_point: Box<models::CompetitiveRoundSummariesUtilityAbilitiesInnerLandingPoint>,
    #[serde(rename = "slot")]
    pub slot: String,
}

impl CompetitiveRoundSummariesUtilityAbilitiesInner {
    pub fn new(cast_position: models::CompetitiveRoundSummariesSmokeAbilitiesInnerCastPosition, landing_point: models::CompetitiveRoundSummariesUtilityAbilitiesInnerLandingPoint, slot: String) -> CompetitiveRoundSummariesUtilityAbilitiesInner {
        CompetitiveRoundSummariesUtilityAbilitiesInner {
            cast_position: Box::new(cast_position),
            landing_point: Box::new(landing_point),
            slot,
        }
    }
}

