/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveTeamRoundSummaries {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "plant_location")]
    pub plant_location: String,
    #[serde(rename = "agents")]
    pub agents: String,
    #[serde(rename = "weapons")]
    pub weapons: String,
    #[serde(rename = "players")]
    pub players: String,
    #[serde(rename = "win", skip_serializing_if = "Option::is_none")]
    pub win: Option<i32>,
    #[serde(rename = "round_end", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub round_end: Option<Option<String>>,
    #[serde(rename = "round_eco_type")]
    pub round_eco_type: String,
    #[serde(rename = "round_eco_type_no_bonus")]
    pub round_eco_type_no_bonus: String,
    #[serde(rename = "side")]
    pub side: String,
    #[serde(rename = "loadout_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub loadout_value: Option<Option<i64>>,
    #[serde(rename = "investment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub investment: Option<Option<i64>>,
    #[serde(rename = "kills")]
    pub kills: i32,
    #[serde(rename = "deaths")]
    pub deaths: i32,
    #[serde(rename = "planted_spike", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub planted_spike: Option<Option<bool>>,
    #[serde(rename = "plant_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub plant_time: Option<Option<i32>>,
    #[serde(rename = "bomb_site", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bomb_site: Option<Option<String>>,
    #[serde(rename = "kast", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kast: Option<Option<i32>>,
    #[serde(rename = "assists", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub assists: Option<Option<i32>>,
    #[serde(rename = "damages", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub damages: Option<Option<i32>>,
    #[serde(rename = "combat_score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub combat_score: Option<Option<i32>>,
    #[serde(rename = "first_blood", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_blood: Option<Option<bool>>,
    #[serde(rename = "first_death", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_death: Option<Option<bool>>,
    #[serde(rename = "first_true_blood", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_true_blood: Option<Option<bool>>,
    #[serde(rename = "first_true_death", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_true_death: Option<Option<bool>>,
    #[serde(rename = "attack_pattern_full", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attack_pattern_full: Option<Option<String>>,
    #[serde(rename = "defense_pattern_full", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub defense_pattern_full: Option<Option<String>>,
    #[serde(rename = "attack_pattern_short", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attack_pattern_short: Option<Option<String>>,
    #[serde(rename = "defense_pattern_short", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub defense_pattern_short: Option<Option<String>>,
    #[serde(rename = "round_index")]
    pub round_index: i32,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "game")]
    pub game: String,
    #[serde(rename = "team1")]
    pub team1: String,
    #[serde(rename = "team2")]
    pub team2: String,
    #[serde(rename = "league")]
    pub league: String,
    #[serde(rename = "map")]
    pub map: String,
}

impl CompetitiveTeamRoundSummaries {
    pub fn new(id: String, plant_location: String, agents: String, weapons: String, players: String, round_eco_type: String, round_eco_type_no_bonus: String, side: String, kills: i32, deaths: i32, round_index: i32, date: String, game: String, team1: String, team2: String, league: String, map: String) -> CompetitiveTeamRoundSummaries {
        CompetitiveTeamRoundSummaries {
            id,
            plant_location,
            agents,
            weapons,
            players,
            win: None,
            round_end: None,
            round_eco_type,
            round_eco_type_no_bonus,
            side,
            loadout_value: None,
            investment: None,
            kills,
            deaths,
            planted_spike: None,
            plant_time: None,
            bomb_site: None,
            kast: None,
            assists: None,
            damages: None,
            combat_score: None,
            first_blood: None,
            first_death: None,
            first_true_blood: None,
            first_true_death: None,
            attack_pattern_full: None,
            defense_pattern_full: None,
            attack_pattern_short: None,
            defense_pattern_short: None,
            round_index,
            date,
            game,
            team1,
            team2,
            league,
            map,
        }
    }
}

