/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesPlayerSnapshotsInnerAbilitiesValue {
    #[serde(rename = "slot")]
    pub slot: String,
    #[serde(rename = "base_charges")]
    pub base_charges: i32,
    #[serde(rename = "max_charges")]
    pub max_charges: i32,
    #[serde(rename = "temporary_charges")]
    pub temporary_charges: i32,
}

impl CompetitiveRoundSummariesPlayerSnapshotsInnerAbilitiesValue {
    pub fn new(slot: String, base_charges: i32, max_charges: i32, temporary_charges: i32) -> CompetitiveRoundSummariesPlayerSnapshotsInnerAbilitiesValue {
        CompetitiveRoundSummariesPlayerSnapshotsInnerAbilitiesValue {
            slot,
            base_charges,
            max_charges,
            temporary_charges,
        }
    }
}

