/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItem {
    #[serde(rename = "ammunition")]
    pub ammunition: Box<models::CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItemAmmunition>,
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "slot", deserialize_with = "Option::deserialize")]
    pub slot: Option<String>,
}

impl CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItem {
    pub fn new(ammunition: models::CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItemAmmunition, id: Option<String>, name: Option<String>, slot: Option<String>) -> CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItem {
        CompetitiveRoundSummariesPlayerSnapshotsInnerAliveStateEquippedItem {
            ammunition: Box::new(ammunition),
            id,
            name,
            slot,
        }
    }
}

