/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitiveRoundSummariesDeathEventInnerAssistantsInner {
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "player")]
    pub player: String,
    #[serde(rename = "weapon")]
    pub weapon: String,
}

impl CompetitiveRoundSummariesDeathEventInnerAssistantsInner {
    pub fn new(agent: String, player: String, weapon: String) -> CompetitiveRoundSummariesDeathEventInnerAssistantsInner {
        CompetitiveRoundSummariesDeathEventInnerAssistantsInner {
            agent,
            player,
            weapon,
        }
    }
}

