/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Gear {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cost: Option<Option<i32>>,
    #[serde(rename = "display_icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_icon: Option<Option<String>>,
}

impl Gear {
    pub fn new(id: String, uuid: String) -> Gear {
        Gear {
            id,
            uuid,
            description: None,
            cost: None,
            display_icon: None,
        }
    }
}

