/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct League {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "full_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<Option<String>>,
    #[serde(rename = "shortened", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shortened: Option<Option<String>>,
    #[serde(rename = "region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub region: Option<Option<String>>,
    #[serde(rename = "current_teams", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_teams: Option<Option<String>>,
    #[serde(rename = "logo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo: Option<Option<String>>,
    #[serde(rename = "track_players", skip_serializing_if = "Option::is_none")]
    pub track_players: Option<bool>,
    #[serde(rename = "league_group", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub league_group: Option<Option<String>>,
}

impl League {
    pub fn new(id: String) -> League {
        League {
            id,
            full_name: None,
            shortened: None,
            region: None,
            current_teams: None,
            logo: None,
            track_players: None,
            league_group: None,
        }
    }
}

