/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkRiotAccountResponse : Riot account data that was stored on the user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkRiotAccountResponse {
    #[serde(rename = "riot_puuid")]
    pub riot_puuid: String,
    #[serde(rename = "riot_gamename", deserialize_with = "Option::deserialize")]
    pub riot_gamename: Option<String>,
    #[serde(rename = "riot_tagline", deserialize_with = "Option::deserialize")]
    pub riot_tagline: Option<String>,
}

impl LinkRiotAccountResponse {
    /// Riot account data that was stored on the user.
    pub fn new(riot_puuid: String, riot_gamename: Option<String>, riot_tagline: Option<String>) -> LinkRiotAccountResponse {
        LinkRiotAccountResponse {
            riot_puuid,
            riot_gamename,
            riot_tagline,
        }
    }
}

