/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkRiotAccountRequest : Payload sent by the frontend after completing the RSO OAuth2 flow.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkRiotAccountRequest {
    /// RSO access token returned by the Riot OAuth2 token endpoint.
    #[serde(rename = "access_token")]
    pub access_token: String,
    /// RSO refresh token returned by the Riot OAuth2 token endpoint.
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    /// Access token lifetime in seconds, as returned by the token endpoint.
    #[serde(rename = "expires_in")]
    pub expires_in: i32,
}

impl LinkRiotAccountRequest {
    /// Payload sent by the frontend after completing the RSO OAuth2 flow.
    pub fn new(access_token: String, refresh_token: String, expires_in: i32) -> LinkRiotAccountRequest {
        LinkRiotAccountRequest {
            access_token,
            refresh_token,
            expires_in,
        }
    }
}

