/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Login {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "user_id")]
    pub user_id: i32,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "team")]
    pub team: String,
    #[serde(rename = "organization")]
    pub organization: String,
    #[serde(rename = "is_staff")]
    pub is_staff: bool,
    #[serde(rename = "is_org_owner")]
    pub is_org_owner: bool,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "date_joined")]
    pub date_joined: String,
    #[serde(rename = "draft_model_displayed")]
    pub draft_model_displayed: String,
    #[serde(rename = "riot_gamename", deserialize_with = "Option::deserialize")]
    pub riot_gamename: Option<String>,
    #[serde(rename = "riot_tagline", deserialize_with = "Option::deserialize")]
    pub riot_tagline: Option<String>,
}

impl Login {
    pub fn new(username: String, password: String, token: String, user_id: i32, email: String, team: String, organization: String, is_staff: bool, is_org_owner: bool, is_active: bool, date_joined: String, draft_model_displayed: String, riot_gamename: Option<String>, riot_tagline: Option<String>) -> Login {
        Login {
            username,
            password,
            token,
            user_id,
            email,
            team,
            organization,
            is_staff,
            is_org_owner,
            is_active,
            date_joined,
            draft_model_displayed,
            riot_gamename,
            riot_tagline,
        }
    }
}

