/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MapsAggregate {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "image", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image: Option<Option<String>>,
    #[serde(rename = "min_x")]
    pub min_x: i32,
    #[serde(rename = "max_x")]
    pub max_x: i32,
    #[serde(rename = "min_y")]
    pub min_y: i32,
    #[serde(rename = "max_y")]
    pub max_y: i32,
    #[serde(rename = "x_multiplier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub x_multiplier: Option<Option<f64>>,
    #[serde(rename = "y_multiplier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub y_multiplier: Option<Option<f64>>,
    #[serde(rename = "x_scalar_to_add", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub x_scalar_to_add: Option<Option<f64>>,
    #[serde(rename = "y_scalar_to_add", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub y_scalar_to_add: Option<Option<f64>>,
    #[serde(rename = "uuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<Option<String>>,
}

impl MapsAggregate {
    pub fn new(id: String, min_x: i32, max_x: i32, min_y: i32, max_y: i32) -> MapsAggregate {
        MapsAggregate {
            id,
            image: None,
            min_x,
            max_x,
            min_y,
            max_y,
            x_multiplier: None,
            y_multiplier: None,
            x_scalar_to_add: None,
            y_scalar_to_add: None,
            uuid: None,
        }
    }
}

