/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedClientOrganization {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<String>,
    #[serde(rename = "grid_api_key", skip_serializing_if = "Option::is_none")]
    pub grid_api_key: Option<String>,
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<String>,
    #[serde(rename = "subscription_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subscription_date: Option<Option<String>>,
    #[serde(rename = "subscription_ends", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subscription_ends: Option<Option<String>>,
}

impl PatchedClientOrganization {
    pub fn new() -> PatchedClientOrganization {
        PatchedClientOrganization {
            id: None,
            teams: None,
            grid_api_key: None,
            plan: None,
            subscription_date: None,
            subscription_ends: None,
        }
    }
}

