/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedSoloQAccounts {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "puuid", skip_serializing_if = "Option::is_none")]
    pub puuid: Option<String>,
    #[serde(rename = "account_name", skip_serializing_if = "Option::is_none")]
    pub account_name: Option<String>,
    #[serde(rename = "rank_tier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rank_tier: Option<Option<i32>>,
    #[serde(rename = "ranked_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ranked_rating: Option<Option<i32>>,
    #[serde(rename = "server", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub server: Option<Option<String>>,
    #[serde(rename = "last_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<Option<String>>,
    #[serde(rename = "player", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub player: Option<Option<String>>,
}

impl PatchedSoloQAccounts {
    pub fn new() -> PatchedSoloQAccounts {
        PatchedSoloQAccounts {
            id: None,
            puuid: None,
            account_name: None,
            rank_tier: None,
            ranked_rating: None,
            server: None,
            last_updated: None,
            player: None,
        }
    }
}

