/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedUser {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "team", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub team: Option<Option<String>>,
    #[serde(rename = "organization", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Option<String>>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "is_staff", skip_serializing_if = "Option::is_none")]
    pub is_staff: Option<bool>,
    #[serde(rename = "is_org_owner", skip_serializing_if = "Option::is_none")]
    pub is_org_owner: Option<bool>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "date_joined", skip_serializing_if = "Option::is_none")]
    pub date_joined: Option<String>,
    #[serde(rename = "riot_puuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub riot_puuid: Option<Option<String>>,
    #[serde(rename = "riot_gamename", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub riot_gamename: Option<Option<String>>,
    #[serde(rename = "riot_tagline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub riot_tagline: Option<Option<String>>,
}

impl PatchedUser {
    pub fn new() -> PatchedUser {
        PatchedUser {
            id: None,
            email: None,
            team: None,
            organization: None,
            username: None,
            is_staff: None,
            is_org_owner: None,
            is_active: None,
            date_joined: None,
            riot_puuid: None,
            riot_gamename: None,
            riot_tagline: None,
        }
    }
}

