/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayerAggregate {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "grid_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub grid_id: Option<Option<i32>>,
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<String>>,
    #[serde(rename = "previous_names", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub previous_names: Option<Option<String>>,
    #[serde(rename = "birthdate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub birthdate: Option<Option<String>>,
    #[serde(rename = "nationality", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nationality: Option<Option<String>>,
    #[serde(rename = "contract_expires", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contract_expires: Option<Option<String>>,
    #[serde(rename = "twitter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub twitter: Option<Option<String>>,
    #[serde(rename = "last_competitive_game", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_competitive_game: Option<Option<String>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "image", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image: Option<Option<String>>,
    #[serde(rename = "real_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub real_name: Option<Option<String>>,
    #[serde(rename = "is_sub", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_sub: Option<Option<bool>>,
    #[serde(rename = "is_retired", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_retired: Option<Option<bool>>,
    #[serde(rename = "discord", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub discord: Option<Option<String>>,
    #[serde(rename = "stream", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stream: Option<Option<String>>,
    #[serde(rename = "soloq_tracked", skip_serializing_if = "Option::is_none")]
    pub soloq_tracked: Option<bool>,
    #[serde(rename = "current_team", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_team: Option<Option<String>>,
    #[serde(rename = "domestic_league", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domestic_league: Option<Option<String>>,
    #[serde(rename = "last_team", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_team: Option<Option<String>>,
}

impl PlayerAggregate {
    pub fn new(id: String) -> PlayerAggregate {
        PlayerAggregate {
            id,
            grid_id: None,
            role: None,
            previous_names: None,
            birthdate: None,
            nationality: None,
            contract_expires: None,
            twitter: None,
            last_competitive_game: None,
            source: None,
            image: None,
            real_name: None,
            is_sub: None,
            is_retired: None,
            discord: None,
            stream: None,
            soloq_tracked: None,
            current_team: None,
            domestic_league: None,
            last_team: None,
        }
    }
}

