/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// RankTierEnum : * `0` - Unranked0 * `1` - Unranked1 * `2` - Unranked2 * `3` - Iron 1 * `4` - Iron 2 * `5` - Iron 3 * `6` - Bronze 1 * `7` - Bronze 2 * `8` - Bronze 3 * `9` - Silver 1 * `10` - Silver 2 * `11` - Silver 3 * `12` - Gold 1 * `13` - Gold 2 * `14` - Gold 3 * `15` - Plat 1 * `16` - Plat 2 * `17` - Plat 3 * `18` - Diamond 1 * `19` - Diamond 2 * `20` - Diamond 3 * `21` - Ascendant 1 * `22` - Ascendant 2 * `23` - Ascendant 3 * `24` - Immortal 1 * `25` - Immortal 2 * `26` - Immortal 3 * `27` - Radiant
/// * `0` - Unranked0 * `1` - Unranked1 * `2` - Unranked2 * `3` - Iron 1 * `4` - Iron 2 * `5` - Iron 3 * `6` - Bronze 1 * `7` - Bronze 2 * `8` - Bronze 3 * `9` - Silver 1 * `10` - Silver 2 * `11` - Silver 3 * `12` - Gold 1 * `13` - Gold 2 * `14` - Gold 3 * `15` - Plat 1 * `16` - Plat 2 * `17` - Plat 3 * `18` - Diamond 1 * `19` - Diamond 2 * `20` - Diamond 3 * `21` - Ascendant 1 * `22` - Ascendant 2 * `23` - Ascendant 3 * `24` - Immortal 1 * `25` - Immortal 2 * `26` - Immortal 3 * `27` - Radiant
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum RankTierEnum {
    Variant0 = 0,
    Variant1 = 1,
    Variant2 = 2,
    Variant3 = 3,
    Variant4 = 4,
    Variant5 = 5,
    Variant6 = 6,
    Variant7 = 7,
    Variant8 = 8,
    Variant9 = 9,
    Variant10 = 10,
    Variant11 = 11,
    Variant12 = 12,
    Variant13 = 13,
    Variant14 = 14,
    Variant15 = 15,
    Variant16 = 16,
    Variant17 = 17,
    Variant18 = 18,
    Variant19 = 19,
    Variant20 = 20,
    Variant21 = 21,
    Variant22 = 22,
    Variant23 = 23,
    Variant24 = 24,
    Variant25 = 25,
    Variant26 = 26,
    Variant27 = 27,

}

impl std::fmt::Display for RankTierEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
            Self::Variant2 => "2",
            Self::Variant3 => "3",
            Self::Variant4 => "4",
            Self::Variant5 => "5",
            Self::Variant6 => "6",
            Self::Variant7 => "7",
            Self::Variant8 => "8",
            Self::Variant9 => "9",
            Self::Variant10 => "10",
            Self::Variant11 => "11",
            Self::Variant12 => "12",
            Self::Variant13 => "13",
            Self::Variant14 => "14",
            Self::Variant15 => "15",
            Self::Variant16 => "16",
            Self::Variant17 => "17",
            Self::Variant18 => "18",
            Self::Variant19 => "19",
            Self::Variant20 => "20",
            Self::Variant21 => "21",
            Self::Variant22 => "22",
            Self::Variant23 => "23",
            Self::Variant24 => "24",
            Self::Variant25 => "25",
            Self::Variant26 => "26",
            Self::Variant27 => "27",
        })
    }
}
impl Default for RankTierEnum {
    fn default() -> RankTierEnum {
        Self::Variant0
    }
}

