/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScrimGameSummaries {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "patch")]
    pub patch: String,
    #[serde(rename = "kills")]
    pub kills: i32,
    #[serde(rename = "deaths")]
    pub deaths: i32,
    #[serde(rename = "assists")]
    pub assists: i32,
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "kpr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kpr: Option<Option<f64>>,
    #[serde(rename = "dpr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dpr: Option<Option<f64>>,
    #[serde(rename = "impact", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub impact: Option<Option<f64>>,
    #[serde(rename = "adr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub adr: Option<Option<f64>>,
    #[serde(rename = "kast", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kast: Option<Option<f64>>,
    #[serde(rename = "rating_hltv", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating_hltv: Option<Option<f64>>,
    #[serde(rename = "combat_score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub combat_score: Option<Option<f64>>,
    #[serde(rename = "win")]
    pub win: bool,
    #[serde(rename = "participant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub participant_id: Option<Option<i32>>,
    #[serde(rename = "acs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub acs: Option<Option<f64>>,
    #[serde(rename = "headshot_percent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub headshot_percent: Option<Option<f64>>,
    #[serde(rename = "headshots", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub headshots: Option<Option<i32>>,
    #[serde(rename = "first_kills", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_kills: Option<Option<f64>>,
    #[serde(rename = "first_deaths", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_deaths: Option<Option<f64>>,
    #[serde(rename = "got_traded", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub got_traded: Option<Option<i32>>,
    #[serde(rename = "rounds_played", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rounds_played: Option<Option<i32>>,
    #[serde(rename = "rounds_won", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rounds_won: Option<Option<i32>>,
    #[serde(rename = "rounds_lost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rounds_lost: Option<Option<i32>>,
    #[serde(rename = "game_id")]
    pub game_id: String,
    #[serde(rename = "ig_name")]
    pub ig_name: String,
    #[serde(rename = "player")]
    pub player: String,
    #[serde(rename = "team1")]
    pub team1: String,
    #[serde(rename = "team2")]
    pub team2: String,
    #[serde(rename = "map")]
    pub map: String,
}

impl ScrimGameSummaries {
    pub fn new(id: String, date: String, patch: String, kills: i32, deaths: i32, assists: i32, agent: String, win: bool, game_id: String, ig_name: String, player: String, team1: String, team2: String, map: String) -> ScrimGameSummaries {
        ScrimGameSummaries {
            id,
            date,
            patch,
            kills,
            deaths,
            assists,
            agent,
            kpr: None,
            dpr: None,
            impact: None,
            adr: None,
            kast: None,
            rating_hltv: None,
            combat_score: None,
            win,
            participant_id: None,
            acs: None,
            headshot_percent: None,
            headshots: None,
            first_kills: None,
            first_deaths: None,
            got_traded: None,
            rounds_played: None,
            rounds_won: None,
            rounds_lost: None,
            game_id,
            ig_name,
            player,
            team1,
            team2,
            map,
        }
    }
}

