/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SoloQGamesAggregate {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "agnostic_match_history", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub agnostic_match_history: Option<Option<String>>,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "score_team1")]
    pub score_team1: i32,
    #[serde(rename = "score_team2")]
    pub score_team2: i32,
    #[serde(rename = "winner")]
    pub winner: String,
    #[serde(rename = "team1_agents")]
    pub team1_agents: String,
    #[serde(rename = "team2_agents")]
    pub team2_agents: String,
    #[serde(rename = "map")]
    pub map: String,
}

impl SoloQGamesAggregate {
    pub fn new(id: String, date: String, score_team1: i32, score_team2: i32, winner: String, team1_agents: String, team2_agents: String, map: String) -> SoloQGamesAggregate {
        SoloQGamesAggregate {
            id,
            agnostic_match_history: None,
            date,
            score_team1,
            score_team2,
            winner,
            team1_agents,
            team2_agents,
            map,
        }
    }
}

