/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SoloQAccounts {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "puuid")]
    pub puuid: String,
    #[serde(rename = "account_name")]
    pub account_name: String,
    #[serde(rename = "rank_tier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rank_tier: Option<Option<i32>>,
    #[serde(rename = "server", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub server: Option<Option<String>>,
    #[serde(rename = "player", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub player: Option<Option<String>>,
}

impl SoloQAccounts {
    pub fn new(id: i32, puuid: String, account_name: String) -> SoloQAccounts {
        SoloQAccounts {
            id,
            puuid,
            account_name,
            rank_tier: None,
            server: None,
            player: None,
        }
    }
}

