/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SoloQGameSummariesAggregate {
    #[serde(rename = "pk")]
    pub pk: String,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "patch")]
    pub patch: String,
    #[serde(rename = "kills")]
    pub kills: i32,
    #[serde(rename = "deaths")]
    pub deaths: i32,
    #[serde(rename = "assists")]
    pub assists: i32,
    #[serde(rename = "kpr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kpr: Option<Option<f64>>,
    #[serde(rename = "dpr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dpr: Option<Option<f64>>,
    #[serde(rename = "impact", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub impact: Option<Option<f64>>,
    #[serde(rename = "adr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub adr: Option<Option<f64>>,
    #[serde(rename = "kast", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kast: Option<Option<f64>>,
    #[serde(rename = "rating_hltv", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating_hltv: Option<Option<f64>>,
    #[serde(rename = "rating_vlr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating_vlr: Option<Option<f64>>,
    #[serde(rename = "combat_score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub combat_score: Option<Option<f64>>,
    #[serde(rename = "win")]
    pub win: bool,
    #[serde(rename = "acs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub acs: Option<Option<f64>>,
    #[serde(rename = "headshot_percent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub headshot_percent: Option<Option<f64>>,
    #[serde(rename = "headshots", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub headshots: Option<Option<i32>>,
    #[serde(rename = "first_kills", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_kills: Option<Option<f64>>,
    #[serde(rename = "first_deaths", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_deaths: Option<Option<f64>>,
    #[serde(rename = "got_traded", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub got_traded: Option<Option<i32>>,
    #[serde(rename = "rounds_played", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rounds_played: Option<Option<i32>>,
    #[serde(rename = "rounds_won", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rounds_won: Option<Option<i32>>,
    #[serde(rename = "rounds_lost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rounds_lost: Option<Option<i32>>,
    #[serde(rename = "game_id")]
    pub game_id: uuid::Uuid,
    #[serde(rename = "participant_id")]
    pub participant_id: i32,
    #[serde(rename = "rank_tier")]
    pub rank_tier: models::RankTierEnum,
    #[serde(rename = "server")]
    pub server: String,
    #[serde(rename = "ig_name")]
    pub ig_name: String,
    #[serde(rename = "puuid")]
    pub puuid: String,
    #[serde(rename = "team")]
    pub team: models::TeamEnum,
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "competitive_player", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub competitive_player: Option<Option<String>>,
    #[serde(rename = "account", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account: Option<Option<i32>>,
    #[serde(rename = "map")]
    pub map: String,
}

impl SoloQGameSummariesAggregate {
    pub fn new(pk: String, date: String, patch: String, kills: i32, deaths: i32, assists: i32, win: bool, game_id: uuid::Uuid, participant_id: i32, rank_tier: models::RankTierEnum, server: String, ig_name: String, puuid: String, team: models::TeamEnum, agent: String, map: String) -> SoloQGameSummariesAggregate {
        SoloQGameSummariesAggregate {
            pk,
            date,
            patch,
            kills,
            deaths,
            assists,
            kpr: None,
            dpr: None,
            impact: None,
            adr: None,
            kast: None,
            rating_hltv: None,
            rating_vlr: None,
            combat_score: None,
            win,
            acs: None,
            headshot_percent: None,
            headshots: None,
            first_kills: None,
            first_deaths: None,
            got_traded: None,
            rounds_played: None,
            rounds_won: None,
            rounds_lost: None,
            game_id,
            participant_id,
            rank_tier,
            server,
            ig_name,
            puuid,
            team,
            agent,
            competitive_player: None,
            account: None,
            map,
        }
    }
}

