/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SoloQAccountsAggregate {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "puuid")]
    pub puuid: String,
    #[serde(rename = "account_name")]
    pub account_name: String,
    #[serde(rename = "rank_tier")]
    pub rank_tier: i32,
    #[serde(rename = "player_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub player_id: Option<Option<String>>,
    #[serde(rename = "server")]
    pub server: String,
}

impl SoloQAccountsAggregate {
    pub fn new(id: i32, puuid: String, account_name: String, rank_tier: i32, server: String) -> SoloQAccountsAggregate {
        SoloQAccountsAggregate {
            id,
            puuid,
            account_name,
            rank_tier,
            player_id: None,
            server,
        }
    }
}

