/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// TeamEnum : * `1` - 1 * `2` - 2
/// * `1` - 1 * `2` - 2
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum TeamEnum {
    Variant1 = 1,
    Variant2 = 2,

}

impl std::fmt::Display for TeamEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant1 => "1",
            Self::Variant2 => "2",
        })
    }
}
impl Default for TeamEnum {
    fn default() -> TeamEnum {
        Self::Variant1
    }
}

