/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Team {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "logo_url")]
    pub logo_url: String,
    #[serde(rename = "logo_primary")]
    pub logo_primary: String,
    #[serde(rename = "logo_secondary")]
    pub logo_secondary: String,
    #[serde(rename = "current_main_players", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_main_players: Option<Option<String>>,
    #[serde(rename = "players_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub players_list: Option<Option<String>>,
    #[serde(rename = "coaching_staff", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub coaching_staff: Option<Option<String>>,
    #[serde(rename = "manager_discord", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub manager_discord: Option<Option<String>>,
    #[serde(rename = "grid_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub grid_id: Option<Option<i64>>,
    #[serde(rename = "domestic_league", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domestic_league: Option<Option<String>>,
    #[serde(rename = "current_league", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_league: Option<Option<String>>,
    #[serde(rename = "next_opponent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_opponent: Option<Option<String>>,
    #[serde(rename = "renamed_to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub renamed_to: Option<Option<String>>,
}

impl Team {
    pub fn new(id: String, name: String, logo_url: String, logo_primary: String, logo_secondary: String) -> Team {
        Team {
            id,
            name,
            logo_url,
            logo_primary,
            logo_secondary,
            current_main_players: None,
            players_list: None,
            coaching_staff: None,
            manager_discord: None,
            grid_id: None,
            domestic_league: None,
            current_league: None,
            next_opponent: None,
            renamed_to: None,
        }
    }
}

