/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnlinkedAccount {
    #[serde(rename = "puuid")]
    pub puuid: String,
    #[serde(rename = "account_name")]
    pub account_name: String,
}

impl UnlinkedAccount {
    pub fn new(puuid: String, account_name: String) -> UnlinkedAccount {
        UnlinkedAccount {
            puuid,
            account_name,
        }
    }
}

