/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnresolvedAccount {
    #[serde(rename = "client_puuid")]
    pub client_puuid: String,
    #[serde(rename = "account_name")]
    pub account_name: String,
    #[serde(rename = "error")]
    pub error: String,
}

impl UnresolvedAccount {
    pub fn new(client_puuid: String, account_name: String, error: String) -> UnresolvedAccount {
        UnresolvedAccount {
            client_puuid,
            account_name,
            error,
        }
    }
}

