/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadScrimGameError {
    /// Description of what went wrong
    #[serde(rename = "error")]
    pub error: String,
    /// Present when SoloQAccounts are missing player_id links
    #[serde(rename = "unlinked_accounts", skip_serializing_if = "Option::is_none")]
    pub unlinked_accounts: Option<Vec<models::UnlinkedAccount>>,
}

impl UploadScrimGameError {
    pub fn new(error: String) -> UploadScrimGameError {
        UploadScrimGameError {
            error,
            unlinked_accounts: None,
        }
    }
}

