/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeaponsAggregate {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "category", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category: Option<Option<String>>,
    #[serde(rename = "cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cost: Option<Option<i32>>,
    #[serde(rename = "display_icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_icon: Option<Option<String>>,
    #[serde(rename = "kill_stream_icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kill_stream_icon: Option<Option<String>>,
    #[serde(rename = "weapon_stats", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weapon_stats: Option<Option<serde_json::Value>>,
}

impl WeaponsAggregate {
    pub fn new(id: String, uuid: String) -> WeaponsAggregate {
        WeaponsAggregate {
            id,
            uuid,
            category: None,
            cost: None,
            display_icon: None,
            kill_stream_icon: None,
            weapon_stats: None,
        }
    }
}

