/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`competitive_round_summaries_aggregate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveRoundSummariesAggregateError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_round_summaries_field_values`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveRoundSummariesFieldValuesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_round_summaries_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveRoundSummariesGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_round_summaries_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveRoundSummariesListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_round_summaries_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveRoundSummariesVariableDistributionError {
    UnknownValue(serde_json::Value),
}


pub async fn competitive_round_summaries_aggregate(configuration: &configuration::Configuration, groupby: Vec<String>, ordering: Vec<String>, additional_filters: Option<serde_json::Value>, agent: Option<&str>, aggregates: Option<Vec<String>>, attack_pattern_full: Option<&str>, attack_pattern_short: Option<&str>, bomb_site: Option<&str>, callout_15s: Option<&str>, date: Option<String>, defense_pattern_full: Option<&str>, defense_pattern_short: Option<&str>, first_attack_site: Option<&str>, freeze_time_end_timestamp: Option<i32>, game: Option<&str>, having: Option<serde_json::Value>, index_on: Option<&str>, league: Option<&str>, map: Option<&str>, metrics: Option<Vec<String>>, patch: Option<&str>, plant_time: Option<i32>, player: Option<&str>, round_eco_type: Option<&str>, round_eco_type_no_bonus: Option<&str>, round_id: Option<&str>, round_index: Option<i32>, shield: Option<&str>, side: Option<&str>, start_time_seconds: Option<i32>, summary: Option<&str>, team1: Option<&str>, team2: Option<&str>) -> Result<Vec<models::CompetitiveRoundSummariesAggregate>, Error<CompetitiveRoundSummariesAggregateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_groupby = groupby;
    let p_query_ordering = ordering;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_aggregates = aggregates;
    let p_query_attack_pattern_full = attack_pattern_full;
    let p_query_attack_pattern_short = attack_pattern_short;
    let p_query_bomb_site = bomb_site;
    let p_query_callout_15s = callout_15s;
    let p_query_date = date;
    let p_query_defense_pattern_full = defense_pattern_full;
    let p_query_defense_pattern_short = defense_pattern_short;
    let p_query_first_attack_site = first_attack_site;
    let p_query_freeze_time_end_timestamp = freeze_time_end_timestamp;
    let p_query_game = game;
    let p_query_having = having;
    let p_query_index_on = index_on;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_metrics = metrics;
    let p_query_patch = patch;
    let p_query_plant_time = plant_time;
    let p_query_player = player;
    let p_query_round_eco_type = round_eco_type;
    let p_query_round_eco_type_no_bonus = round_eco_type_no_bonus;
    let p_query_round_id = round_id;
    let p_query_round_index = round_index;
    let p_query_shield = shield;
    let p_query_side = side;
    let p_query_start_time_seconds = start_time_seconds;
    let p_query_summary = summary;
    let p_query_team1 = team1;
    let p_query_team2 = team2;

    let uri_str = format!("{}/CompetitiveRoundSummaries/operations/aggregate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_aggregates {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("aggregates".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("aggregates", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_attack_pattern_full {
        req_builder = req_builder.query(&[("attack_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_short {
        req_builder = req_builder.query(&[("attack_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bomb_site {
        req_builder = req_builder.query(&[("bomb_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_callout_15s {
        req_builder = req_builder.query(&[("callout_15s", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_full {
        req_builder = req_builder.query(&[("defense_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_short {
        req_builder = req_builder.query(&[("defense_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_attack_site {
        req_builder = req_builder.query(&[("first_attack_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_freeze_time_end_timestamp {
        req_builder = req_builder.query(&[("freeze_time_end_timestamp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game {
        req_builder = req_builder.query(&[("game", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_groupby.into_iter().map(|p| ("groupby".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("groupby", &p_query_groupby.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_having {
        req_builder = req_builder.query(&[("having", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_index_on {
        req_builder = req_builder.query(&[("index_on", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_metrics {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("metrics".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("metrics", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_ordering.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("ordering", &p_query_ordering.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_plant_time {
        req_builder = req_builder.query(&[("plant_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type {
        req_builder = req_builder.query(&[("round_eco_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type_no_bonus {
        req_builder = req_builder.query(&[("round_eco_type_no_bonus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_id {
        req_builder = req_builder.query(&[("round_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_index {
        req_builder = req_builder.query(&[("round_index", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_shield {
        req_builder = req_builder.query(&[("shield", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_side {
        req_builder = req_builder.query(&[("side", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time_seconds {
        req_builder = req_builder.query(&[("start_time_seconds", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_summary {
        req_builder = req_builder.query(&[("summary", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CompetitiveRoundSummariesAggregate&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CompetitiveRoundSummariesAggregate&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveRoundSummariesAggregateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_round_summaries_field_values(configuration: &configuration::Configuration, field: &str, ordering: Vec<String>, additional_filters: Option<serde_json::Value>, agent: Option<&str>, attack_pattern_full: Option<&str>, attack_pattern_short: Option<&str>, bomb_site: Option<&str>, callout_15s: Option<&str>, date: Option<String>, defense_pattern_full: Option<&str>, defense_pattern_short: Option<&str>, first_attack_site: Option<&str>, freeze_time_end_timestamp: Option<i32>, game: Option<&str>, league: Option<&str>, map: Option<&str>, patch: Option<&str>, plant_time: Option<i32>, player: Option<&str>, round_eco_type: Option<&str>, round_eco_type_no_bonus: Option<&str>, round_id: Option<&str>, round_index: Option<i32>, shield: Option<&str>, side: Option<&str>, start_time_seconds: Option<i32>, summary: Option<&str>, team1: Option<&str>, team2: Option<&str>) -> Result<Vec<String>, Error<CompetitiveRoundSummariesFieldValuesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_field = field;
    let p_query_ordering = ordering;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_attack_pattern_full = attack_pattern_full;
    let p_query_attack_pattern_short = attack_pattern_short;
    let p_query_bomb_site = bomb_site;
    let p_query_callout_15s = callout_15s;
    let p_query_date = date;
    let p_query_defense_pattern_full = defense_pattern_full;
    let p_query_defense_pattern_short = defense_pattern_short;
    let p_query_first_attack_site = first_attack_site;
    let p_query_freeze_time_end_timestamp = freeze_time_end_timestamp;
    let p_query_game = game;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_patch = patch;
    let p_query_plant_time = plant_time;
    let p_query_player = player;
    let p_query_round_eco_type = round_eco_type;
    let p_query_round_eco_type_no_bonus = round_eco_type_no_bonus;
    let p_query_round_id = round_id;
    let p_query_round_index = round_index;
    let p_query_shield = shield;
    let p_query_side = side;
    let p_query_start_time_seconds = start_time_seconds;
    let p_query_summary = summary;
    let p_query_team1 = team1;
    let p_query_team2 = team2;

    let uri_str = format!("{}/CompetitiveRoundSummaries/operations/field-values", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_full {
        req_builder = req_builder.query(&[("attack_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_short {
        req_builder = req_builder.query(&[("attack_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bomb_site {
        req_builder = req_builder.query(&[("bomb_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_callout_15s {
        req_builder = req_builder.query(&[("callout_15s", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_full {
        req_builder = req_builder.query(&[("defense_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_short {
        req_builder = req_builder.query(&[("defense_pattern_short", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("field", &p_query_field.to_string())]);
    if let Some(ref param_value) = p_query_first_attack_site {
        req_builder = req_builder.query(&[("first_attack_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_freeze_time_end_timestamp {
        req_builder = req_builder.query(&[("freeze_time_end_timestamp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game {
        req_builder = req_builder.query(&[("game", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_ordering.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("ordering", &p_query_ordering.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_plant_time {
        req_builder = req_builder.query(&[("plant_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type {
        req_builder = req_builder.query(&[("round_eco_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type_no_bonus {
        req_builder = req_builder.query(&[("round_eco_type_no_bonus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_id {
        req_builder = req_builder.query(&[("round_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_index {
        req_builder = req_builder.query(&[("round_index", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_shield {
        req_builder = req_builder.query(&[("shield", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_side {
        req_builder = req_builder.query(&[("side", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time_seconds {
        req_builder = req_builder.query(&[("start_time_seconds", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_summary {
        req_builder = req_builder.query(&[("summary", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;String&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;String&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveRoundSummariesFieldValuesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_round_summaries_get(configuration: &configuration::Configuration, id: &str) -> Result<models::CompetitiveRoundSummaries, Error<CompetitiveRoundSummariesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/CompetitiveRoundSummaries/item/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CompetitiveRoundSummaries`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CompetitiveRoundSummaries`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveRoundSummariesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_round_summaries_list(configuration: &configuration::Configuration, additional_filters: Option<serde_json::Value>, agent: Option<&str>, annotations: Option<Vec<String>>, attack_pattern_full: Option<&str>, attack_pattern_short: Option<&str>, bomb_site: Option<&str>, callout_15s: Option<&str>, date: Option<String>, defense_pattern_full: Option<&str>, defense_pattern_short: Option<&str>, first_attack_site: Option<&str>, freeze_time_end_timestamp: Option<i32>, game: Option<&str>, league: Option<&str>, map: Option<&str>, only_values: Option<Vec<String>>, ordering: Option<Vec<String>>, patch: Option<&str>, plant_time: Option<i32>, player: Option<&str>, round_eco_type: Option<&str>, round_eco_type_no_bonus: Option<&str>, round_id: Option<&str>, round_index: Option<i32>, shield: Option<&str>, side: Option<&str>, start_time_seconds: Option<i32>, summary: Option<&str>, team1: Option<&str>, team2: Option<&str>) -> Result<Vec<models::CompetitiveRoundSummaries>, Error<CompetitiveRoundSummariesListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_annotations = annotations;
    let p_query_attack_pattern_full = attack_pattern_full;
    let p_query_attack_pattern_short = attack_pattern_short;
    let p_query_bomb_site = bomb_site;
    let p_query_callout_15s = callout_15s;
    let p_query_date = date;
    let p_query_defense_pattern_full = defense_pattern_full;
    let p_query_defense_pattern_short = defense_pattern_short;
    let p_query_first_attack_site = first_attack_site;
    let p_query_freeze_time_end_timestamp = freeze_time_end_timestamp;
    let p_query_game = game;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_only_values = only_values;
    let p_query_ordering = ordering;
    let p_query_patch = patch;
    let p_query_plant_time = plant_time;
    let p_query_player = player;
    let p_query_round_eco_type = round_eco_type;
    let p_query_round_eco_type_no_bonus = round_eco_type_no_bonus;
    let p_query_round_id = round_id;
    let p_query_round_index = round_index;
    let p_query_shield = shield;
    let p_query_side = side;
    let p_query_start_time_seconds = start_time_seconds;
    let p_query_summary = summary;
    let p_query_team1 = team1;
    let p_query_team2 = team2;

    let uri_str = format!("{}/CompetitiveRoundSummaries/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_annotations {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("annotations".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("annotations", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_attack_pattern_full {
        req_builder = req_builder.query(&[("attack_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_short {
        req_builder = req_builder.query(&[("attack_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bomb_site {
        req_builder = req_builder.query(&[("bomb_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_callout_15s {
        req_builder = req_builder.query(&[("callout_15s", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_full {
        req_builder = req_builder.query(&[("defense_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_short {
        req_builder = req_builder.query(&[("defense_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_attack_site {
        req_builder = req_builder.query(&[("first_attack_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_freeze_time_end_timestamp {
        req_builder = req_builder.query(&[("freeze_time_end_timestamp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game {
        req_builder = req_builder.query(&[("game", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_only_values {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("only_values".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("only_values", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_ordering {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("ordering", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_plant_time {
        req_builder = req_builder.query(&[("plant_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type {
        req_builder = req_builder.query(&[("round_eco_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type_no_bonus {
        req_builder = req_builder.query(&[("round_eco_type_no_bonus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_id {
        req_builder = req_builder.query(&[("round_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_index {
        req_builder = req_builder.query(&[("round_index", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_shield {
        req_builder = req_builder.query(&[("shield", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_side {
        req_builder = req_builder.query(&[("side", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time_seconds {
        req_builder = req_builder.query(&[("start_time_seconds", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_summary {
        req_builder = req_builder.query(&[("summary", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CompetitiveRoundSummaries&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CompetitiveRoundSummaries&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveRoundSummariesListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_round_summaries_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, agent: Option<&str>, attack_pattern_full: Option<&str>, attack_pattern_short: Option<&str>, bomb_site: Option<&str>, callout_15s: Option<&str>, date: Option<String>, defense_pattern_full: Option<&str>, defense_pattern_short: Option<&str>, first_attack_site: Option<&str>, freeze_time_end_timestamp: Option<i32>, game: Option<&str>, league: Option<&str>, map: Option<&str>, patch: Option<&str>, plant_time: Option<i32>, player: Option<&str>, round_eco_type: Option<&str>, round_eco_type_no_bonus: Option<&str>, round_id: Option<&str>, round_index: Option<i32>, shield: Option<&str>, side: Option<&str>, start_time_seconds: Option<i32>, summary: Option<&str>, team1: Option<&str>, team2: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<CompetitiveRoundSummariesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_attack_pattern_full = attack_pattern_full;
    let p_query_attack_pattern_short = attack_pattern_short;
    let p_query_bomb_site = bomb_site;
    let p_query_callout_15s = callout_15s;
    let p_query_date = date;
    let p_query_defense_pattern_full = defense_pattern_full;
    let p_query_defense_pattern_short = defense_pattern_short;
    let p_query_first_attack_site = first_attack_site;
    let p_query_freeze_time_end_timestamp = freeze_time_end_timestamp;
    let p_query_game = game;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_patch = patch;
    let p_query_plant_time = plant_time;
    let p_query_player = player;
    let p_query_round_eco_type = round_eco_type;
    let p_query_round_eco_type_no_bonus = round_eco_type_no_bonus;
    let p_query_round_id = round_id;
    let p_query_round_index = round_index;
    let p_query_shield = shield;
    let p_query_side = side;
    let p_query_start_time_seconds = start_time_seconds;
    let p_query_summary = summary;
    let p_query_team1 = team1;
    let p_query_team2 = team2;

    let uri_str = format!("{}/CompetitiveRoundSummaries/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_full {
        req_builder = req_builder.query(&[("attack_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_short {
        req_builder = req_builder.query(&[("attack_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bomb_site {
        req_builder = req_builder.query(&[("bomb_site", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_callout_15s {
        req_builder = req_builder.query(&[("callout_15s", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_full {
        req_builder = req_builder.query(&[("defense_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_short {
        req_builder = req_builder.query(&[("defense_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_attack_site {
        req_builder = req_builder.query(&[("first_attack_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_freeze_time_end_timestamp {
        req_builder = req_builder.query(&[("freeze_time_end_timestamp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game {
        req_builder = req_builder.query(&[("game", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_plant_time {
        req_builder = req_builder.query(&[("plant_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type {
        req_builder = req_builder.query(&[("round_eco_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type_no_bonus {
        req_builder = req_builder.query(&[("round_eco_type_no_bonus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_id {
        req_builder = req_builder.query(&[("round_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_index {
        req_builder = req_builder.query(&[("round_index", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_shield {
        req_builder = req_builder.query(&[("shield", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_side {
        req_builder = req_builder.query(&[("side", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time_seconds {
        req_builder = req_builder.query(&[("start_time_seconds", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_summary {
        req_builder = req_builder.query(&[("summary", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveRoundSummariesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

