/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`competitive_draft_slots_aggregate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveDraftSlotsAggregateError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_draft_slots_field_values`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveDraftSlotsFieldValuesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_draft_slots_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveDraftSlotsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_draft_slots_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveDraftSlotsListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_draft_slots_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveDraftSlotsVariableDistributionError {
    UnknownValue(serde_json::Value),
}


pub async fn competitive_draft_slots_aggregate(configuration: &configuration::Configuration, groupby: Vec<String>, ordering: Vec<String>, additional_filters: Option<serde_json::Value>, aggregates: Option<Vec<String>>, draft_action_id: Option<&str>, having: Option<serde_json::Value>, index_on: Option<&str>, league: Option<&str>, map: Option<&str>, metrics: Option<Vec<String>>, phase: Option<&str>, series: Option<i32>, split: Option<&str>, team1: Option<&str>, team2: Option<&str>, teams: Option<&str>, r#type: Option<&str>) -> Result<Vec<models::CompetitiveDraftSlotsAggregate>, Error<CompetitiveDraftSlotsAggregateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_groupby = groupby;
    let p_query_ordering = ordering;
    let p_query_additional_filters = additional_filters;
    let p_query_aggregates = aggregates;
    let p_query_draft_action_id = draft_action_id;
    let p_query_having = having;
    let p_query_index_on = index_on;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_metrics = metrics;
    let p_query_phase = phase;
    let p_query_series = series;
    let p_query_split = split;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_teams = teams;
    let p_query_type = r#type;

    let uri_str = format!("{}/CompetitiveDraftSlots/operations/aggregate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        req_builder = req_builder.query(&[("additional_filters", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_aggregates {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("aggregates".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("aggregates", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_draft_action_id {
        req_builder = req_builder.query(&[("draft_action_id", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_groupby.into_iter().map(|p| ("groupby".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("groupby", &p_query_groupby.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_having {
        req_builder = req_builder.query(&[("having", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_index_on {
        req_builder = req_builder.query(&[("index_on", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_metrics {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("metrics".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("metrics", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_ordering.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("ordering", &p_query_ordering.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_phase {
        req_builder = req_builder.query(&[("phase", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_series {
        req_builder = req_builder.query(&[("series", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_split {
        req_builder = req_builder.query(&[("split", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_teams {
        req_builder = req_builder.query(&[("teams", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_type {
        req_builder = req_builder.query(&[("type", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CompetitiveDraftSlotsAggregate&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CompetitiveDraftSlotsAggregate&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveDraftSlotsAggregateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_draft_slots_field_values(configuration: &configuration::Configuration, field: &str, ordering: Vec<String>, additional_filters: Option<serde_json::Value>, draft_action_id: Option<&str>, league: Option<&str>, map: Option<&str>, phase: Option<&str>, series: Option<i32>, split: Option<&str>, team1: Option<&str>, team2: Option<&str>, teams: Option<&str>, r#type: Option<&str>) -> Result<Vec<String>, Error<CompetitiveDraftSlotsFieldValuesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_field = field;
    let p_query_ordering = ordering;
    let p_query_additional_filters = additional_filters;
    let p_query_draft_action_id = draft_action_id;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_phase = phase;
    let p_query_series = series;
    let p_query_split = split;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_teams = teams;
    let p_query_type = r#type;

    let uri_str = format!("{}/CompetitiveDraftSlots/operations/field-values", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        req_builder = req_builder.query(&[("additional_filters", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_draft_action_id {
        req_builder = req_builder.query(&[("draft_action_id", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("field", &p_query_field.to_string())]);
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_ordering.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("ordering", &p_query_ordering.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_phase {
        req_builder = req_builder.query(&[("phase", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_series {
        req_builder = req_builder.query(&[("series", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_split {
        req_builder = req_builder.query(&[("split", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_teams {
        req_builder = req_builder.query(&[("teams", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_type {
        req_builder = req_builder.query(&[("type", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;String&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;String&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveDraftSlotsFieldValuesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_draft_slots_get(configuration: &configuration::Configuration, id: &str) -> Result<models::CompetitiveDraftSlots, Error<CompetitiveDraftSlotsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/CompetitiveDraftSlots/item/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CompetitiveDraftSlots`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CompetitiveDraftSlots`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveDraftSlotsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_draft_slots_list(configuration: &configuration::Configuration, additional_filters: Option<serde_json::Value>, annotations: Option<Vec<String>>, draft_action_id: Option<&str>, league: Option<&str>, map: Option<&str>, only_values: Option<Vec<String>>, ordering: Option<Vec<String>>, phase: Option<&str>, series: Option<i32>, split: Option<&str>, team1: Option<&str>, team2: Option<&str>, teams: Option<&str>, r#type: Option<&str>) -> Result<Vec<models::CompetitiveDraftSlots>, Error<CompetitiveDraftSlotsListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_additional_filters = additional_filters;
    let p_query_annotations = annotations;
    let p_query_draft_action_id = draft_action_id;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_only_values = only_values;
    let p_query_ordering = ordering;
    let p_query_phase = phase;
    let p_query_series = series;
    let p_query_split = split;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_teams = teams;
    let p_query_type = r#type;

    let uri_str = format!("{}/CompetitiveDraftSlots/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        req_builder = req_builder.query(&[("additional_filters", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_annotations {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("annotations".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("annotations", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_draft_action_id {
        req_builder = req_builder.query(&[("draft_action_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_only_values {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("only_values".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("only_values", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_ordering {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("ordering", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_phase {
        req_builder = req_builder.query(&[("phase", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_series {
        req_builder = req_builder.query(&[("series", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_split {
        req_builder = req_builder.query(&[("split", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_teams {
        req_builder = req_builder.query(&[("teams", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_type {
        req_builder = req_builder.query(&[("type", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CompetitiveDraftSlots&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CompetitiveDraftSlots&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveDraftSlotsListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_draft_slots_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, draft_action_id: Option<&str>, league: Option<&str>, map: Option<&str>, phase: Option<&str>, series: Option<i32>, split: Option<&str>, team1: Option<&str>, team2: Option<&str>, teams: Option<&str>, r#type: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<CompetitiveDraftSlotsVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_draft_action_id = draft_action_id;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_phase = phase;
    let p_query_series = series;
    let p_query_split = split;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_teams = teams;
    let p_query_type = r#type;

    let uri_str = format!("{}/CompetitiveDraftSlots/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        req_builder = req_builder.query(&[("additional_filters", &serde_json::to_string(param_value)?)]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_draft_action_id {
        req_builder = req_builder.query(&[("draft_action_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_phase {
        req_builder = req_builder.query(&[("phase", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_series {
        req_builder = req_builder.query(&[("series", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_split {
        req_builder = req_builder.query(&[("split", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_teams {
        req_builder = req_builder.query(&[("teams", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_type {
        req_builder = req_builder.query(&[("type", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveDraftSlotsVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

