/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */


/// Base URL for the development backend (localhost).
pub const BASE_URL_DEV: &str = "http://localhost:8000";

/// Base URL for the production backend.
pub const BASE_URL_PROD: &str = "https://api.reckon-bolt.com";

#[derive(Debug, Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub bearer_access_token: Option<String>,
    pub api_key: Option<ApiKey>,
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }

    /// Create a configuration pointing at the **development** backend.
    pub fn dev() -> Configuration {
        Configuration {
            base_path: BASE_URL_DEV.to_owned(),
            ..Default::default()
        }
    }

    /// Create a configuration pointing at the **production** backend.
    pub fn prod() -> Configuration {
        Configuration {
            base_path: BASE_URL_PROD.to_owned(),
            ..Default::default()
        }
    }

    /// Create a configuration with a custom base URL.
    pub fn with_base_url(base_url: &str) -> Configuration {
        Configuration {
            base_path: base_url.to_owned(),
            ..Default::default()
        }
    }

    /// Set the API token for authentication (token auth).
    pub fn with_token(mut self, token: &str) -> Configuration {
        self.api_key = Some(ApiKey {
            prefix: Some("Token".to_owned()),
            key: token.to_owned(),
        });
        self
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: BASE_URL_DEV.to_owned(),
            user_agent: Some("ReckonBoltApp/1.0.0".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: None,
            api_key: None,
        }
    }
}