/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`link_riot_account_create`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LinkRiotAccountCreateError {
    UnknownValue(serde_json::Value),
}


/// Link the authenticated user's account to their Riot Games identity.  The frontend redirects the user to Riot's authorization page. After the user authorizes, the frontend receives an authorization code and sends it here. The backend then:  1. Exchanges the authorization code for access / refresh tokens via the    Riot RSO token endpoint. 2. Uses the access token to retrieve the player's PUUID, game name and    tagline from the Riot Account API. 3. Persists everything on the ``AuthUser`` model for later use (e.g. fetching    match history, including private games).
pub async fn link_riot_account_create(configuration: &configuration::Configuration, link_riot_account_request: models::LinkRiotAccountRequest) -> Result<models::LinkRiotAccountResponse, Error<LinkRiotAccountCreateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_link_riot_account_request = link_riot_account_request;

    let uri_str = format!("{}/LinkRiotAccount", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_link_riot_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LinkRiotAccountResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LinkRiotAccountResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LinkRiotAccountCreateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

