/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`solo_q_game_summaries_aggregate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SoloQGameSummariesAggregateError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`solo_q_game_summaries_field_values`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SoloQGameSummariesFieldValuesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`solo_q_game_summaries_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SoloQGameSummariesGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`solo_q_game_summaries_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SoloQGameSummariesListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`solo_q_game_summaries_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SoloQGameSummariesVariableDistributionError {
    UnknownValue(serde_json::Value),
}


pub async fn solo_q_game_summaries_aggregate(configuration: &configuration::Configuration, groupby: Vec<String>, ordering: Vec<String>, account: Option<i32>, additional_filters: Option<serde_json::Value>, agent: Option<&str>, aggregates: Option<Vec<String>>, competitive_player: Option<&str>, date: Option<String>, game_id: Option<&str>, having: Option<serde_json::Value>, ig_name: Option<&str>, index_on: Option<&str>, map: Option<&str>, metrics: Option<Vec<String>>, patch: Option<&str>, puuid: Option<&str>, rank_tier: Option<i32>, server: Option<&str>, team: Option<i32>, win: Option<bool>) -> Result<Vec<models::SoloQGameSummariesAggregate>, Error<SoloQGameSummariesAggregateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_groupby = groupby;
    let p_query_ordering = ordering;
    let p_query_account = account;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_aggregates = aggregates;
    let p_query_competitive_player = competitive_player;
    let p_query_date = date;
    let p_query_game_id = game_id;
    let p_query_having = having;
    let p_query_ig_name = ig_name;
    let p_query_index_on = index_on;
    let p_query_map = map;
    let p_query_metrics = metrics;
    let p_query_patch = patch;
    let p_query_puuid = puuid;
    let p_query_rank_tier = rank_tier;
    let p_query_server = server;
    let p_query_team = team;
    let p_query_win = win;

    let uri_str = format!("{}/SoloQGameSummaries/operations/aggregate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_account {
        req_builder = req_builder.query(&[("account", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_aggregates {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("aggregates".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("aggregates", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_competitive_player {
        req_builder = req_builder.query(&[("competitive_player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game_id {
        req_builder = req_builder.query(&[("game_id", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_groupby.into_iter().map(|p| ("groupby".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("groupby", &p_query_groupby.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_having {
        req_builder = req_builder.query(&[("having", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_ig_name {
        req_builder = req_builder.query(&[("ig_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_index_on {
        req_builder = req_builder.query(&[("index_on", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_metrics {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("metrics".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("metrics", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_ordering.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("ordering", &p_query_ordering.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_puuid {
        req_builder = req_builder.query(&[("puuid", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_rank_tier {
        req_builder = req_builder.query(&[("rank_tier", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_server {
        req_builder = req_builder.query(&[("server", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team {
        req_builder = req_builder.query(&[("team", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_win {
        req_builder = req_builder.query(&[("win", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::SoloQGameSummariesAggregate&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::SoloQGameSummariesAggregate&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SoloQGameSummariesAggregateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn solo_q_game_summaries_field_values(configuration: &configuration::Configuration, field: &str, ordering: Vec<String>, account: Option<i32>, additional_filters: Option<serde_json::Value>, agent: Option<&str>, competitive_player: Option<&str>, date: Option<String>, game_id: Option<&str>, ig_name: Option<&str>, map: Option<&str>, patch: Option<&str>, puuid: Option<&str>, rank_tier: Option<i32>, server: Option<&str>, team: Option<i32>, win: Option<bool>) -> Result<Vec<String>, Error<SoloQGameSummariesFieldValuesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_field = field;
    let p_query_ordering = ordering;
    let p_query_account = account;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_competitive_player = competitive_player;
    let p_query_date = date;
    let p_query_game_id = game_id;
    let p_query_ig_name = ig_name;
    let p_query_map = map;
    let p_query_patch = patch;
    let p_query_puuid = puuid;
    let p_query_rank_tier = rank_tier;
    let p_query_server = server;
    let p_query_team = team;
    let p_query_win = win;

    let uri_str = format!("{}/SoloQGameSummaries/operations/field-values", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_account {
        req_builder = req_builder.query(&[("account", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_competitive_player {
        req_builder = req_builder.query(&[("competitive_player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("field", &p_query_field.to_string())]);
    if let Some(ref param_value) = p_query_game_id {
        req_builder = req_builder.query(&[("game_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_ig_name {
        req_builder = req_builder.query(&[("ig_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_ordering.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("ordering", &p_query_ordering.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_puuid {
        req_builder = req_builder.query(&[("puuid", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_rank_tier {
        req_builder = req_builder.query(&[("rank_tier", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_server {
        req_builder = req_builder.query(&[("server", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team {
        req_builder = req_builder.query(&[("team", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_win {
        req_builder = req_builder.query(&[("win", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;String&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;String&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SoloQGameSummariesFieldValuesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn solo_q_game_summaries_get(configuration: &configuration::Configuration, id: &str) -> Result<models::SoloQGameSummaries, Error<SoloQGameSummariesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/SoloQGameSummaries/item/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SoloQGameSummaries`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SoloQGameSummaries`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SoloQGameSummariesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn solo_q_game_summaries_list(configuration: &configuration::Configuration, account: Option<i32>, additional_filters: Option<serde_json::Value>, agent: Option<&str>, annotations: Option<Vec<String>>, competitive_player: Option<&str>, date: Option<String>, game_id: Option<&str>, ig_name: Option<&str>, map: Option<&str>, only_values: Option<Vec<String>>, ordering: Option<Vec<String>>, patch: Option<&str>, puuid: Option<&str>, rank_tier: Option<i32>, server: Option<&str>, team: Option<i32>, win: Option<bool>) -> Result<Vec<models::SoloQGameSummaries>, Error<SoloQGameSummariesListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_account = account;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_annotations = annotations;
    let p_query_competitive_player = competitive_player;
    let p_query_date = date;
    let p_query_game_id = game_id;
    let p_query_ig_name = ig_name;
    let p_query_map = map;
    let p_query_only_values = only_values;
    let p_query_ordering = ordering;
    let p_query_patch = patch;
    let p_query_puuid = puuid;
    let p_query_rank_tier = rank_tier;
    let p_query_server = server;
    let p_query_team = team;
    let p_query_win = win;

    let uri_str = format!("{}/SoloQGameSummaries/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_account {
        req_builder = req_builder.query(&[("account", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_annotations {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("annotations".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("annotations", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_competitive_player {
        req_builder = req_builder.query(&[("competitive_player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game_id {
        req_builder = req_builder.query(&[("game_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_ig_name {
        req_builder = req_builder.query(&[("ig_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_only_values {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("only_values".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("only_values", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_ordering {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("ordering", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_puuid {
        req_builder = req_builder.query(&[("puuid", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_rank_tier {
        req_builder = req_builder.query(&[("rank_tier", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_server {
        req_builder = req_builder.query(&[("server", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team {
        req_builder = req_builder.query(&[("team", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_win {
        req_builder = req_builder.query(&[("win", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::SoloQGameSummaries&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::SoloQGameSummaries&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SoloQGameSummariesListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn solo_q_game_summaries_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, account: Option<i32>, additional_filters: Option<serde_json::Value>, agent: Option<&str>, competitive_player: Option<&str>, date: Option<String>, game_id: Option<&str>, ig_name: Option<&str>, map: Option<&str>, patch: Option<&str>, puuid: Option<&str>, rank_tier: Option<i32>, server: Option<&str>, team: Option<i32>, win: Option<bool>) -> Result<Vec<models::AgentVariableDistribution200ResponseInner>, Error<SoloQGameSummariesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_account = account;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_competitive_player = competitive_player;
    let p_query_date = date;
    let p_query_game_id = game_id;
    let p_query_ig_name = ig_name;
    let p_query_map = map;
    let p_query_patch = patch;
    let p_query_puuid = puuid;
    let p_query_rank_tier = rank_tier;
    let p_query_server = server;
    let p_query_team = team;
    let p_query_win = win;

    let uri_str = format!("{}/SoloQGameSummaries/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_account {
        req_builder = req_builder.query(&[("account", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_competitive_player {
        req_builder = req_builder.query(&[("competitive_player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game_id {
        req_builder = req_builder.query(&[("game_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_ig_name {
        req_builder = req_builder.query(&[("ig_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_puuid {
        req_builder = req_builder.query(&[("puuid", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_rank_tier {
        req_builder = req_builder.query(&[("rank_tier", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_server {
        req_builder = req_builder.query(&[("server", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team {
        req_builder = req_builder.query(&[("team", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_win {
        req_builder = req_builder.query(&[("win", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::AgentVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::AgentVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SoloQGameSummariesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

