/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`team_aggregate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TeamAggregateError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`team_field_values`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TeamFieldValuesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`team_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TeamGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`team_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TeamListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`team_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TeamPatchError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`team_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TeamVariableDistributionError {
    UnknownValue(serde_json::Value),
}


pub async fn team_aggregate(configuration: &configuration::Configuration, groupby: Vec<String>, ordering: Vec<String>, additional_filters: Option<serde_json::Value>, aggregates: Option<Vec<String>>, coaching_staff: Option<&str>, current_league: Option<&str>, current_main_players: Option<&str>, domestic_league: Option<&str>, grid_id: Option<i32>, having: Option<serde_json::Value>, id: Option<&str>, index_on: Option<&str>, metrics: Option<Vec<String>>, name: Option<&str>, next_opponent: Option<&str>, players_list: Option<&str>, renamed_to: Option<&str>) -> Result<Vec<models::TeamAggregate>, Error<TeamAggregateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_groupby = groupby;
    let p_query_ordering = ordering;
    let p_query_additional_filters = additional_filters;
    let p_query_aggregates = aggregates;
    let p_query_coaching_staff = coaching_staff;
    let p_query_current_league = current_league;
    let p_query_current_main_players = current_main_players;
    let p_query_domestic_league = domestic_league;
    let p_query_grid_id = grid_id;
    let p_query_having = having;
    let p_query_id = id;
    let p_query_index_on = index_on;
    let p_query_metrics = metrics;
    let p_query_name = name;
    let p_query_next_opponent = next_opponent;
    let p_query_players_list = players_list;
    let p_query_renamed_to = renamed_to;

    let uri_str = format!("{}/Team/operations/aggregate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_aggregates {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("aggregates".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("aggregates", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_coaching_staff {
        req_builder = req_builder.query(&[("coaching_staff", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_league {
        req_builder = req_builder.query(&[("current_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_main_players {
        req_builder = req_builder.query(&[("current_main_players", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_domestic_league {
        req_builder = req_builder.query(&[("domestic_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_grid_id {
        req_builder = req_builder.query(&[("grid_id", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_groupby.into_iter().map(|p| ("groupby".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("groupby", &p_query_groupby.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_having {
        req_builder = req_builder.query(&[("having", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_index_on {
        req_builder = req_builder.query(&[("index_on", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_metrics {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("metrics".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("metrics", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_next_opponent {
        req_builder = req_builder.query(&[("next_opponent", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_ordering.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("ordering", &p_query_ordering.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_players_list {
        req_builder = req_builder.query(&[("players_list", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_renamed_to {
        req_builder = req_builder.query(&[("renamed_to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::TeamAggregate&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::TeamAggregate&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TeamAggregateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn team_field_values(configuration: &configuration::Configuration, field: &str, ordering: Vec<String>, additional_filters: Option<serde_json::Value>, coaching_staff: Option<&str>, current_league: Option<&str>, current_main_players: Option<&str>, domestic_league: Option<&str>, grid_id: Option<i32>, id: Option<&str>, name: Option<&str>, next_opponent: Option<&str>, players_list: Option<&str>, renamed_to: Option<&str>) -> Result<Vec<String>, Error<TeamFieldValuesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_field = field;
    let p_query_ordering = ordering;
    let p_query_additional_filters = additional_filters;
    let p_query_coaching_staff = coaching_staff;
    let p_query_current_league = current_league;
    let p_query_current_main_players = current_main_players;
    let p_query_domestic_league = domestic_league;
    let p_query_grid_id = grid_id;
    let p_query_id = id;
    let p_query_name = name;
    let p_query_next_opponent = next_opponent;
    let p_query_players_list = players_list;
    let p_query_renamed_to = renamed_to;

    let uri_str = format!("{}/Team/operations/field-values", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_coaching_staff {
        req_builder = req_builder.query(&[("coaching_staff", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_league {
        req_builder = req_builder.query(&[("current_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_main_players {
        req_builder = req_builder.query(&[("current_main_players", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_domestic_league {
        req_builder = req_builder.query(&[("domestic_league", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("field", &p_query_field.to_string())]);
    if let Some(ref param_value) = p_query_grid_id {
        req_builder = req_builder.query(&[("grid_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_next_opponent {
        req_builder = req_builder.query(&[("next_opponent", &param_value.to_string())]);
    }
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_ordering.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("ordering", &p_query_ordering.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_players_list {
        req_builder = req_builder.query(&[("players_list", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_renamed_to {
        req_builder = req_builder.query(&[("renamed_to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;String&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;String&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TeamFieldValuesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn team_get(configuration: &configuration::Configuration, id: &str) -> Result<models::Team, Error<TeamGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/Team/item/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Team`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Team`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TeamGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn team_list(configuration: &configuration::Configuration, additional_filters: Option<serde_json::Value>, annotations: Option<Vec<String>>, coaching_staff: Option<&str>, current_league: Option<&str>, current_main_players: Option<&str>, domestic_league: Option<&str>, grid_id: Option<i32>, id: Option<&str>, name: Option<&str>, next_opponent: Option<&str>, only_values: Option<Vec<String>>, ordering: Option<Vec<String>>, players_list: Option<&str>, renamed_to: Option<&str>) -> Result<Vec<models::Team>, Error<TeamListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_additional_filters = additional_filters;
    let p_query_annotations = annotations;
    let p_query_coaching_staff = coaching_staff;
    let p_query_current_league = current_league;
    let p_query_current_main_players = current_main_players;
    let p_query_domestic_league = domestic_league;
    let p_query_grid_id = grid_id;
    let p_query_id = id;
    let p_query_name = name;
    let p_query_next_opponent = next_opponent;
    let p_query_only_values = only_values;
    let p_query_ordering = ordering;
    let p_query_players_list = players_list;
    let p_query_renamed_to = renamed_to;

    let uri_str = format!("{}/Team/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_annotations {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("annotations".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("annotations", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_coaching_staff {
        req_builder = req_builder.query(&[("coaching_staff", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_league {
        req_builder = req_builder.query(&[("current_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_main_players {
        req_builder = req_builder.query(&[("current_main_players", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_domestic_league {
        req_builder = req_builder.query(&[("domestic_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_grid_id {
        req_builder = req_builder.query(&[("grid_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_next_opponent {
        req_builder = req_builder.query(&[("next_opponent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_only_values {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("only_values".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("only_values", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_ordering {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("ordering".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("ordering", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_players_list {
        req_builder = req_builder.query(&[("players_list", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_renamed_to {
        req_builder = req_builder.query(&[("renamed_to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Team&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Team&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TeamListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn team_patch(configuration: &configuration::Configuration, id: &str, patched_team: Option<models::PatchedTeam>) -> Result<models::Team, Error<TeamPatchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_patched_team = patched_team;

    let uri_str = format!("{}/Team/item/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_patched_team);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Team`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Team`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TeamPatchError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn team_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, coaching_staff: Option<&str>, current_league: Option<&str>, current_main_players: Option<&str>, domestic_league: Option<&str>, grid_id: Option<i32>, id: Option<&str>, name: Option<&str>, next_opponent: Option<&str>, players_list: Option<&str>, renamed_to: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<TeamVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_coaching_staff = coaching_staff;
    let p_query_current_league = current_league;
    let p_query_current_main_players = current_main_players;
    let p_query_domestic_league = domestic_league;
    let p_query_grid_id = grid_id;
    let p_query_id = id;
    let p_query_name = name;
    let p_query_next_opponent = next_opponent;
    let p_query_players_list = players_list;
    let p_query_renamed_to = renamed_to;

    let uri_str = format!("{}/Team/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_coaching_staff {
        req_builder = req_builder.query(&[("coaching_staff", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_league {
        req_builder = req_builder.query(&[("current_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_main_players {
        req_builder = req_builder.query(&[("current_main_players", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_domestic_league {
        req_builder = req_builder.query(&[("domestic_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_grid_id {
        req_builder = req_builder.query(&[("grid_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_next_opponent {
        req_builder = req_builder.query(&[("next_opponent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_players_list {
        req_builder = req_builder.query(&[("players_list", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_renamed_to {
        req_builder = req_builder.query(&[("renamed_to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TeamVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

