/*
 * Reckon Bolt API
 *
 * Backend API for Reckon Bolt
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`client_organization_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClientOrganizationVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_draft_slots_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveDraftSlotsVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_game_summaries_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveGameSummariesVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_games_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveGamesVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_round_summaries_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveRoundSummariesVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`competitive_team_round_summaries_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompetitiveTeamRoundSummariesVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`game_metrics_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GameMetricsVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`league_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeagueVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`maps_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MapsVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`player_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PlayerVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`scrim_game_summaries_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScrimGameSummariesVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`scrim_games_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScrimGamesVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`scrim_round_summaries_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScrimRoundSummariesVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`scrim_team_round_summaries_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScrimTeamRoundSummariesVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`solo_q_accounts_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SoloQAccountsVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`team_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TeamVariableDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`user_variable_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UserVariableDistributionError {
    UnknownValue(serde_json::Value),
}


pub async fn client_organization_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<ClientOrganizationVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;

    let uri_str = format!("{}/ClientOrganization/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClientOrganizationVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_draft_slots_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, draft_action_id: Option<&str>, league: Option<&str>, map: Option<&str>, phase: Option<&str>, series: Option<i32>, split: Option<&str>, team1: Option<&str>, team2: Option<&str>, teams: Option<&str>, r#type: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<CompetitiveDraftSlotsVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_draft_action_id = draft_action_id;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_phase = phase;
    let p_query_series = series;
    let p_query_split = split;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_teams = teams;
    let p_query_type = r#type;

    let uri_str = format!("{}/CompetitiveDraftSlots/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_draft_action_id {
        req_builder = req_builder.query(&[("draft_action_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_phase {
        req_builder = req_builder.query(&[("phase", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_series {
        req_builder = req_builder.query(&[("series", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_split {
        req_builder = req_builder.query(&[("split", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_teams {
        req_builder = req_builder.query(&[("teams", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_type {
        req_builder = req_builder.query(&[("type", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveDraftSlotsVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_game_summaries_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, agent: Option<&str>, date: Option<String>, id: Option<&str>, league: Option<&str>, map: Option<&str>, patch: Option<&str>, player: Option<&str>, team1: Option<&str>, team2: Option<&str>, win: Option<bool>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<CompetitiveGameSummariesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_date = date;
    let p_query_id = id;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_patch = patch;
    let p_query_player = player;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_win = win;

    let uri_str = format!("{}/CompetitiveGameSummaries/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_win {
        req_builder = req_builder.query(&[("win", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveGameSummariesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_games_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, game_id: Option<&str>, id: Option<&str>, league: Option<&str>, map: Option<&str>, map_selection: Option<&str>, phase: Option<&str>, series_id: Option<i32>, smokes_yolonet_version: Option<&str>, split: Option<&str>, team1: Option<&str>, team2: Option<&str>, utils_yolonet_version: Option<&str>, winner: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<CompetitiveGamesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_game_id = game_id;
    let p_query_id = id;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_map_selection = map_selection;
    let p_query_phase = phase;
    let p_query_series_id = series_id;
    let p_query_smokes_yolonet_version = smokes_yolonet_version;
    let p_query_split = split;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_utils_yolonet_version = utils_yolonet_version;
    let p_query_winner = winner;

    let uri_str = format!("{}/CompetitiveGames/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_game_id {
        req_builder = req_builder.query(&[("game_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map_selection {
        req_builder = req_builder.query(&[("map_selection", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_phase {
        req_builder = req_builder.query(&[("phase", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_series_id {
        req_builder = req_builder.query(&[("series_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_smokes_yolonet_version {
        req_builder = req_builder.query(&[("smokes_yolonet_version", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_split {
        req_builder = req_builder.query(&[("split", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_utils_yolonet_version {
        req_builder = req_builder.query(&[("utils_yolonet_version", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_winner {
        req_builder = req_builder.query(&[("winner", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveGamesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_round_summaries_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, agent: Option<&str>, attack_pattern_full: Option<&str>, attack_pattern_short: Option<&str>, bomb_site: Option<&str>, callout_15s: Option<&str>, date: Option<String>, defense_pattern_full: Option<&str>, defense_pattern_short: Option<&str>, first_attack_site: Option<&str>, freeze_time_end_timestamp: Option<i32>, game: Option<&str>, league: Option<&str>, map: Option<&str>, patch: Option<&str>, plant_time: Option<i32>, player: Option<&str>, round_eco_type: Option<&str>, round_eco_type_no_bonus: Option<&str>, round_id: Option<&str>, round_index: Option<i32>, shield: Option<&str>, side: Option<&str>, start_time_seconds: Option<i32>, summary: Option<&str>, team1: Option<&str>, team2: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<CompetitiveRoundSummariesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_attack_pattern_full = attack_pattern_full;
    let p_query_attack_pattern_short = attack_pattern_short;
    let p_query_bomb_site = bomb_site;
    let p_query_callout_15s = callout_15s;
    let p_query_date = date;
    let p_query_defense_pattern_full = defense_pattern_full;
    let p_query_defense_pattern_short = defense_pattern_short;
    let p_query_first_attack_site = first_attack_site;
    let p_query_freeze_time_end_timestamp = freeze_time_end_timestamp;
    let p_query_game = game;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_patch = patch;
    let p_query_plant_time = plant_time;
    let p_query_player = player;
    let p_query_round_eco_type = round_eco_type;
    let p_query_round_eco_type_no_bonus = round_eco_type_no_bonus;
    let p_query_round_id = round_id;
    let p_query_round_index = round_index;
    let p_query_shield = shield;
    let p_query_side = side;
    let p_query_start_time_seconds = start_time_seconds;
    let p_query_summary = summary;
    let p_query_team1 = team1;
    let p_query_team2 = team2;

    let uri_str = format!("{}/CompetitiveRoundSummaries/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_full {
        req_builder = req_builder.query(&[("attack_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_short {
        req_builder = req_builder.query(&[("attack_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bomb_site {
        req_builder = req_builder.query(&[("bomb_site", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_callout_15s {
        req_builder = req_builder.query(&[("callout_15s", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_full {
        req_builder = req_builder.query(&[("defense_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_short {
        req_builder = req_builder.query(&[("defense_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_attack_site {
        req_builder = req_builder.query(&[("first_attack_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_freeze_time_end_timestamp {
        req_builder = req_builder.query(&[("freeze_time_end_timestamp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game {
        req_builder = req_builder.query(&[("game", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_plant_time {
        req_builder = req_builder.query(&[("plant_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type {
        req_builder = req_builder.query(&[("round_eco_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type_no_bonus {
        req_builder = req_builder.query(&[("round_eco_type_no_bonus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_id {
        req_builder = req_builder.query(&[("round_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_index {
        req_builder = req_builder.query(&[("round_index", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_shield {
        req_builder = req_builder.query(&[("shield", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_side {
        req_builder = req_builder.query(&[("side", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time_seconds {
        req_builder = req_builder.query(&[("start_time_seconds", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_summary {
        req_builder = req_builder.query(&[("summary", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveRoundSummariesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn competitive_team_round_summaries_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, assists: Option<i32>, attack_pattern_full: Option<&str>, attack_pattern_short: Option<&str>, bomb_site: Option<&str>, combat_score: Option<i32>, damages: Option<i32>, date: Option<String>, deaths: Option<i32>, defense_pattern_full: Option<&str>, defense_pattern_short: Option<&str>, first_blood: Option<bool>, first_death: Option<bool>, first_true_blood: Option<bool>, first_true_death: Option<bool>, game: Option<&str>, id: Option<&str>, kast: Option<i32>, kills: Option<i32>, league: Option<&str>, map: Option<&str>, round_eco_type: Option<&str>, round_eco_type_no_bonus: Option<&str>, round_end: Option<&str>, round_index: Option<i32>, side: Option<&str>, team1: Option<&str>, team2: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<CompetitiveTeamRoundSummariesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_assists = assists;
    let p_query_attack_pattern_full = attack_pattern_full;
    let p_query_attack_pattern_short = attack_pattern_short;
    let p_query_bomb_site = bomb_site;
    let p_query_combat_score = combat_score;
    let p_query_damages = damages;
    let p_query_date = date;
    let p_query_deaths = deaths;
    let p_query_defense_pattern_full = defense_pattern_full;
    let p_query_defense_pattern_short = defense_pattern_short;
    let p_query_first_blood = first_blood;
    let p_query_first_death = first_death;
    let p_query_first_true_blood = first_true_blood;
    let p_query_first_true_death = first_true_death;
    let p_query_game = game;
    let p_query_id = id;
    let p_query_kast = kast;
    let p_query_kills = kills;
    let p_query_league = league;
    let p_query_map = map;
    let p_query_round_eco_type = round_eco_type;
    let p_query_round_eco_type_no_bonus = round_eco_type_no_bonus;
    let p_query_round_end = round_end;
    let p_query_round_index = round_index;
    let p_query_side = side;
    let p_query_team1 = team1;
    let p_query_team2 = team2;

    let uri_str = format!("{}/CompetitiveTeamRoundSummaries/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_assists {
        req_builder = req_builder.query(&[("assists", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_full {
        req_builder = req_builder.query(&[("attack_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_short {
        req_builder = req_builder.query(&[("attack_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bomb_site {
        req_builder = req_builder.query(&[("bomb_site", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_combat_score {
        req_builder = req_builder.query(&[("combat_score", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_damages {
        req_builder = req_builder.query(&[("damages", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_deaths {
        req_builder = req_builder.query(&[("deaths", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_full {
        req_builder = req_builder.query(&[("defense_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_short {
        req_builder = req_builder.query(&[("defense_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_blood {
        req_builder = req_builder.query(&[("first_blood", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_death {
        req_builder = req_builder.query(&[("first_death", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_true_blood {
        req_builder = req_builder.query(&[("first_true_blood", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_true_death {
        req_builder = req_builder.query(&[("first_true_death", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game {
        req_builder = req_builder.query(&[("game", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_kast {
        req_builder = req_builder.query(&[("kast", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_kills {
        req_builder = req_builder.query(&[("kills", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league {
        req_builder = req_builder.query(&[("league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_round_eco_type {
        req_builder = req_builder.query(&[("round_eco_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type_no_bonus {
        req_builder = req_builder.query(&[("round_eco_type_no_bonus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_end {
        req_builder = req_builder.query(&[("round_end", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_index {
        req_builder = req_builder.query(&[("round_index", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_side {
        req_builder = req_builder.query(&[("side", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompetitiveTeamRoundSummariesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn game_metrics_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, label: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<GameMetricsVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_label = label;

    let uri_str = format!("{}/GameMetrics/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_label {
        req_builder = req_builder.query(&[("label", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GameMetricsVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn league_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, id: Option<&str>, league_group: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<LeagueVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_id = id;
    let p_query_league_group = league_group;

    let uri_str = format!("{}/League/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_league_group {
        req_builder = req_builder.query(&[("league_group", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeagueVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn maps_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, id: Option<&str>, uuid: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<MapsVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_id = id;
    let p_query_uuid = uuid;

    let uri_str = format!("{}/Maps/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_uuid {
        req_builder = req_builder.query(&[("uuid", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<MapsVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn player_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, birthdate: Option<String>, contract_expires: Option<String>, current_team: Option<&str>, domestic_league: Option<&str>, grid_id: Option<i32>, id: Option<&str>, is_retired: Option<bool>, last_team: Option<&str>, nationality: Option<&str>, previous_names: Option<&str>, role: Option<&str>, soloq_tracked: Option<bool>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<PlayerVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_birthdate = birthdate;
    let p_query_contract_expires = contract_expires;
    let p_query_current_team = current_team;
    let p_query_domestic_league = domestic_league;
    let p_query_grid_id = grid_id;
    let p_query_id = id;
    let p_query_is_retired = is_retired;
    let p_query_last_team = last_team;
    let p_query_nationality = nationality;
    let p_query_previous_names = previous_names;
    let p_query_role = role;
    let p_query_soloq_tracked = soloq_tracked;

    let uri_str = format!("{}/Player/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_birthdate {
        req_builder = req_builder.query(&[("birthdate", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_contract_expires {
        req_builder = req_builder.query(&[("contract_expires", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_team {
        req_builder = req_builder.query(&[("current_team", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_domestic_league {
        req_builder = req_builder.query(&[("domestic_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_grid_id {
        req_builder = req_builder.query(&[("grid_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_retired {
        req_builder = req_builder.query(&[("is_retired", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_last_team {
        req_builder = req_builder.query(&[("last_team", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_nationality {
        req_builder = req_builder.query(&[("nationality", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_previous_names {
        req_builder = req_builder.query(&[("previous_names", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_role {
        req_builder = req_builder.query(&[("role", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_soloq_tracked {
        req_builder = req_builder.query(&[("soloq_tracked", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PlayerVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn scrim_game_summaries_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, agent: Option<&str>, date: Option<String>, id: Option<&str>, map: Option<&str>, patch: Option<&str>, player: Option<&str>, team1: Option<&str>, team2: Option<&str>, win: Option<bool>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<ScrimGameSummariesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_date = date;
    let p_query_id = id;
    let p_query_map = map;
    let p_query_patch = patch;
    let p_query_player = player;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_win = win;

    let uri_str = format!("{}/ScrimGameSummaries/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_win {
        req_builder = req_builder.query(&[("win", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ScrimGameSummariesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn scrim_games_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, id: Option<&str>, map: Option<&str>, team1: Option<&str>, team2: Option<&str>, winner: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<ScrimGamesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_id = id;
    let p_query_map = map;
    let p_query_team1 = team1;
    let p_query_team2 = team2;
    let p_query_winner = winner;

    let uri_str = format!("{}/ScrimGames/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_winner {
        req_builder = req_builder.query(&[("winner", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ScrimGamesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn scrim_round_summaries_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, agent: Option<&str>, attack_pattern_full: Option<&str>, attack_pattern_short: Option<&str>, bomb_site: Option<&str>, callout_15s: Option<&str>, date: Option<String>, defense_pattern_full: Option<&str>, defense_pattern_short: Option<&str>, first_attack_site: Option<&str>, freeze_time_end_timestamp: Option<i32>, game: Option<&str>, map: Option<&str>, patch: Option<&str>, plant_time: Option<i32>, player: Option<&str>, round_eco_type: Option<&str>, round_eco_type_no_bonus: Option<&str>, round_id: Option<&str>, round_index: Option<i32>, shield: Option<&str>, side: Option<&str>, start_time_seconds: Option<i32>, summary: Option<&str>, team1: Option<&str>, team2: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<ScrimRoundSummariesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_agent = agent;
    let p_query_attack_pattern_full = attack_pattern_full;
    let p_query_attack_pattern_short = attack_pattern_short;
    let p_query_bomb_site = bomb_site;
    let p_query_callout_15s = callout_15s;
    let p_query_date = date;
    let p_query_defense_pattern_full = defense_pattern_full;
    let p_query_defense_pattern_short = defense_pattern_short;
    let p_query_first_attack_site = first_attack_site;
    let p_query_freeze_time_end_timestamp = freeze_time_end_timestamp;
    let p_query_game = game;
    let p_query_map = map;
    let p_query_patch = patch;
    let p_query_plant_time = plant_time;
    let p_query_player = player;
    let p_query_round_eco_type = round_eco_type;
    let p_query_round_eco_type_no_bonus = round_eco_type_no_bonus;
    let p_query_round_id = round_id;
    let p_query_round_index = round_index;
    let p_query_shield = shield;
    let p_query_side = side;
    let p_query_start_time_seconds = start_time_seconds;
    let p_query_summary = summary;
    let p_query_team1 = team1;
    let p_query_team2 = team2;

    let uri_str = format!("{}/ScrimRoundSummaries/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_agent {
        req_builder = req_builder.query(&[("agent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_full {
        req_builder = req_builder.query(&[("attack_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_short {
        req_builder = req_builder.query(&[("attack_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bomb_site {
        req_builder = req_builder.query(&[("bomb_site", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_callout_15s {
        req_builder = req_builder.query(&[("callout_15s", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_full {
        req_builder = req_builder.query(&[("defense_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_short {
        req_builder = req_builder.query(&[("defense_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_attack_site {
        req_builder = req_builder.query(&[("first_attack_site", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_freeze_time_end_timestamp {
        req_builder = req_builder.query(&[("freeze_time_end_timestamp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game {
        req_builder = req_builder.query(&[("game", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_patch {
        req_builder = req_builder.query(&[("patch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_plant_time {
        req_builder = req_builder.query(&[("plant_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type {
        req_builder = req_builder.query(&[("round_eco_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type_no_bonus {
        req_builder = req_builder.query(&[("round_eco_type_no_bonus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_id {
        req_builder = req_builder.query(&[("round_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_index {
        req_builder = req_builder.query(&[("round_index", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_shield {
        req_builder = req_builder.query(&[("shield", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_side {
        req_builder = req_builder.query(&[("side", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time_seconds {
        req_builder = req_builder.query(&[("start_time_seconds", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_summary {
        req_builder = req_builder.query(&[("summary", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ScrimRoundSummariesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn scrim_team_round_summaries_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, assists: Option<i32>, attack_pattern_full: Option<&str>, attack_pattern_short: Option<&str>, bomb_site: Option<&str>, combat_score: Option<i32>, damages: Option<i32>, date: Option<String>, deaths: Option<i32>, defense_pattern_full: Option<&str>, defense_pattern_short: Option<&str>, first_blood: Option<bool>, first_death: Option<bool>, first_true_blood: Option<bool>, first_true_death: Option<bool>, game: Option<&str>, id: Option<&str>, kast: Option<i32>, kills: Option<i32>, map: Option<&str>, round_eco_type: Option<&str>, round_eco_type_no_bonus: Option<&str>, round_end: Option<&str>, round_index: Option<i32>, side: Option<&str>, team1: Option<&str>, team2: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<ScrimTeamRoundSummariesVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_assists = assists;
    let p_query_attack_pattern_full = attack_pattern_full;
    let p_query_attack_pattern_short = attack_pattern_short;
    let p_query_bomb_site = bomb_site;
    let p_query_combat_score = combat_score;
    let p_query_damages = damages;
    let p_query_date = date;
    let p_query_deaths = deaths;
    let p_query_defense_pattern_full = defense_pattern_full;
    let p_query_defense_pattern_short = defense_pattern_short;
    let p_query_first_blood = first_blood;
    let p_query_first_death = first_death;
    let p_query_first_true_blood = first_true_blood;
    let p_query_first_true_death = first_true_death;
    let p_query_game = game;
    let p_query_id = id;
    let p_query_kast = kast;
    let p_query_kills = kills;
    let p_query_map = map;
    let p_query_round_eco_type = round_eco_type;
    let p_query_round_eco_type_no_bonus = round_eco_type_no_bonus;
    let p_query_round_end = round_end;
    let p_query_round_index = round_index;
    let p_query_side = side;
    let p_query_team1 = team1;
    let p_query_team2 = team2;

    let uri_str = format!("{}/ScrimTeamRoundSummaries/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    if let Some(ref param_value) = p_query_assists {
        req_builder = req_builder.query(&[("assists", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_full {
        req_builder = req_builder.query(&[("attack_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_attack_pattern_short {
        req_builder = req_builder.query(&[("attack_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bomb_site {
        req_builder = req_builder.query(&[("bomb_site", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_combat_score {
        req_builder = req_builder.query(&[("combat_score", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_damages {
        req_builder = req_builder.query(&[("damages", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date {
        req_builder = req_builder.query(&[("date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_deaths {
        req_builder = req_builder.query(&[("deaths", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_full {
        req_builder = req_builder.query(&[("defense_pattern_full", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_defense_pattern_short {
        req_builder = req_builder.query(&[("defense_pattern_short", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_blood {
        req_builder = req_builder.query(&[("first_blood", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_death {
        req_builder = req_builder.query(&[("first_death", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_true_blood {
        req_builder = req_builder.query(&[("first_true_blood", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_first_true_death {
        req_builder = req_builder.query(&[("first_true_death", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_game {
        req_builder = req_builder.query(&[("game", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_kast {
        req_builder = req_builder.query(&[("kast", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_kills {
        req_builder = req_builder.query(&[("kills", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_map {
        req_builder = req_builder.query(&[("map", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_round_eco_type {
        req_builder = req_builder.query(&[("round_eco_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_eco_type_no_bonus {
        req_builder = req_builder.query(&[("round_eco_type_no_bonus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_end {
        req_builder = req_builder.query(&[("round_end", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_round_index {
        req_builder = req_builder.query(&[("round_index", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_side {
        req_builder = req_builder.query(&[("side", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team1 {
        req_builder = req_builder.query(&[("team1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team2 {
        req_builder = req_builder.query(&[("team2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ScrimTeamRoundSummariesVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn solo_q_accounts_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, player: Option<&str>, puuid: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<SoloQAccountsVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_player = player;
    let p_query_puuid = puuid;

    let uri_str = format!("{}/SoloQAccounts/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_player {
        req_builder = req_builder.query(&[("player", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_puuid {
        req_builder = req_builder.query(&[("puuid", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SoloQAccountsVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn team_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, coaching_staff: Option<&str>, current_league: Option<&str>, current_main_players: Option<&str>, domestic_league: Option<&str>, grid_id: Option<i32>, id: Option<&str>, name: Option<&str>, next_opponent: Option<&str>, players_list: Option<&str>, renamed_to: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<TeamVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_coaching_staff = coaching_staff;
    let p_query_current_league = current_league;
    let p_query_current_main_players = current_main_players;
    let p_query_domestic_league = domestic_league;
    let p_query_grid_id = grid_id;
    let p_query_id = id;
    let p_query_name = name;
    let p_query_next_opponent = next_opponent;
    let p_query_players_list = players_list;
    let p_query_renamed_to = renamed_to;

    let uri_str = format!("{}/Team/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    if let Some(ref param_value) = p_query_coaching_staff {
        req_builder = req_builder.query(&[("coaching_staff", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_league {
        req_builder = req_builder.query(&[("current_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_current_main_players {
        req_builder = req_builder.query(&[("current_main_players", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_domestic_league {
        req_builder = req_builder.query(&[("domestic_league", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_grid_id {
        req_builder = req_builder.query(&[("grid_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_next_opponent {
        req_builder = req_builder.query(&[("next_opponent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_players_list {
        req_builder = req_builder.query(&[("players_list", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_renamed_to {
        req_builder = req_builder.query(&[("renamed_to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TeamVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn user_variable_distribution(configuration: &configuration::Configuration, bucket_size: i32, max: i32, metric: &str, min: i32, additional_filters: Option<serde_json::Value>, organization: Option<&str>, team: Option<&str>) -> Result<Vec<models::ClientOrganizationVariableDistribution200ResponseInner>, Error<UserVariableDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_bucket_size = bucket_size;
    let p_query_max = max;
    let p_query_metric = metric;
    let p_query_min = min;
    let p_query_additional_filters = additional_filters;
    let p_query_organization = organization;
    let p_query_team = team;

    let uri_str = format!("{}/User/operations/variable-distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_additional_filters {
        for (k, v) in crate::apis::additional_filters_query_pairs(param_value) {
            req_builder = req_builder.query(&[(k.as_str(), v.as_str())]);
        }
    }
    req_builder = req_builder.query(&[("bucket_size", &p_query_bucket_size.to_string())]);
    req_builder = req_builder.query(&[("max", &p_query_max.to_string())]);
    req_builder = req_builder.query(&[("metric", &p_query_metric.to_string())]);
    req_builder = req_builder.query(&[("min", &p_query_min.to_string())]);
    if let Some(ref param_value) = p_query_organization {
        req_builder = req_builder.query(&[("organization", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team {
        req_builder = req_builder.query(&[("team", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientOrganizationVariableDistribution200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UserVariableDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

